### ISSUE TITLE
Make "transit" and "pki" backend mount points configurable outside of the code.

### ISSUE THREAD

**Issue by alwaysastudent** [spring-projects/spring-vault#102]
I coming from  https://github.com/spring-cloud/spring-cloud-vault/issues/86#issuecomment-306060960

Currently the `VaultTemplate`bean has got the "transit" and "pki" mount points hardcoded of the default ops methods.  What I feel is that mount points should be configurable and perhaps not be hardcoded like it is on https://github.com/spring-projects/spring-vault/blob/1.0.1.RELEASE/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTemplate.java#L181-L199
```
public class VaultTemplate implements InitializingBean, VaultOperations, DisposableBean {
....
	@Override
	public VaultTransitOperations opsForTransit() {
		return opsForTransit("transit"); // can be defaulted from a configuration
	}

	@Override
	public VaultTransitOperations opsForTransit(String path) {
		return new VaultTransitTemplate(this, path);
	}

	@Override
	public VaultPkiOperations opsForPki() {
		return opsForPki("pki"); // can be defaulted from a configuration
	}

	@Override
	public VaultPkiOperations opsForPki(String path) {
		return new VaultPkiTemplate(this, path);
	}
....
}
```
This would allow the configurations to be derivable from a VCAP_SERVICES env variable on a cloud connector. 

PS. If the paths for the 'transit' and 'pki' are made configurable, I am not sure how the methods opsForTransit(String path) and opsForPki(String path) would fit in gracefully with this design.

**Comment by mp911de** [comment]
We decided to not implement this change. `VaultTemplate` targets the defaults. If defaults are not sufficient, then you can subclass `VaultTemplate` and override methods as necessary.
