### ISSUE TITLE
Release V2 Snapshot

### ISSUE THREAD

**Issue by vbasem** [spring-projects/spring-vault#104]
While we are experimenting with config server from the 2.0 Snapshot branch, vault is the only components which doesn't have a released version compatible with the API. Is it possible to release a snapshot version that we could test with?

thanks.

**Comment by mp911de** [comment]
I'm not sure I understand your requirement. Spring Vault has a [2.0.x](https://github.com/spring-projects/spring-vault/tree/2.0.x) branch. Config server has an integration with Vault but it's not using Spring Vault but rather has its own implementation.

**Comment by vbasem** [comment]
@mp911de it seems I have opened the ticket on the wrong project then. I apologize, let me close it.
