### ISSUE TITLE
XML based Spring configuration

### ISSUE THREAD

**Issue by mrokitka** [spring-projects/spring-vault#114]
It is not clear whether spring-vault supports configuration via Spring XML.  If it does, the documentation should be enhanced to make this explicit and provide examples on how to configure via XML.  If it does not, I propose that XML support be added.

I know Java config is all the rage these days, but basic support via XML should be provided as well.

**Comment by mp911de** [comment]
Spring Vault has no XML configuration component and I don't think that XML config is going to happen unless we find very good reasons. A couple years ago, things were a bit different. We provide `EnvironmentVaultConfiguration` for a minimalistic and convenient configuration approach. 

Care to elaborate why you prefer (require) XML over JavaConfig?

**Comment by mrokitka** [comment]
We have a large number of applications built with Spring, which predate the Java config capability.  The time and risk involved in completely rewriting the bootstrap/config code is substantial.  Lack of XML config support makes this project a non-viable option for would be adopters who must support existing codebases.

**Comment by mp911de** [comment]
You're not required to rewrite your config to JavaConfig but you can keep parts as Java config and pick it up from the XML config with `<context:component-scan base-package="com.example.config" />`.

**Comment by mrokitka** [comment]
Oh, I didn't realize you could integrate like that.  I think that should do.

Thanks!

**Comment by mp911de** [comment]
We decided to not provide XML-based configuration hence closing the ticket.
