### ISSUE TITLE
VaultTransitKeyConfiguration does not match Vault HTTP Transit Key Config API

### ISSUE THREAD

**Issue by gmarziou** [spring-projects/spring-vault#124]
Hello,

[VaultTransitKeyConfiguration](https://github.com/spring-projects/spring-vault/blob/2.0.x/spring-vault-core/src/main/java/org/springframework/vault/support/VaultTransitKeyConfiguration.java) currently only allows to configure 2 settings: "deletion_allowed" and "latest_version" that can be used to update the configuration of a key.

While in Vault 0.7.3, the [transit backend config endpoint](https://www.vaultproject.io/api/secret/transit/index.html#update-key-configuration) allows to set min_decryption_version, min_encryption_version and deletion_allowed.

So it means , we cannot change the min_decryption_version after a key rotation and also that "latest_version" setting is ignored.

**Comment by mp911de** [comment]
Care to submit a pull request? You can always issue an own request posting a `Map<String, Object>` via `VaultTemplate.write(…)` to the appropriate path if the object model provided by Spring Vault does not match the capabilities provided by Vault.

**Comment by gmarziou** [comment]
Good to know.
I can submit a PR but it's going to be a breaking change as latest_version should be removed, or should `VaultTransitKeyConfigurationBuilder latestVersion() ` be `@Deprecated`

**Comment by mp911de** [comment]
We should not break the API, rather add documentation regarding the field validity. `latestVersion` isn't deprecated in the sense of Spring Vault but depends on the used Vault version.

**Comment by gmarziou** [comment]
In the reference doc, I see that Vault at least 0.5 is required, this means that compatibility with almost a dozen of versions should be tested, it seems to be quite a challenging task especially when I cannot find any mention of latest_version change in [vault changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md).

Maybe spring-vault-core 2.0.0 should require more recent versions of Vault?

**Comment by mp911de** [comment]
We have a [range of Vault versions](https://github.com/spring-projects/spring-vault/blob/master/.travis.yml#L17-L25) in our TravisCI build which leverages testing efforts. Providing a driver-like library is always a compatibility dance between various versions.

**Comment by gmarziou** [comment]
Excellent. 
It seems to be even more difficult because Vault ignores silently unknown properties in request payloads.
Anyway I'll try to submit a PR for it.

**Comment by gmarziou** [comment]
I added the "min_decryption_version" and "min_encryption_version" parameters to Transit key configuration request and I have few remarks:

1. I have added a test for `min_decryption_version` but I am unable to test `min_encryption_version` because the  `VaultTransitOperations#encrypt()` method does not offer any way to set a key version unlike the [HTTP API](https://www.vaultproject.io/api/secret/transit/index.html#encrypt-data). Maybe it should be added to `VaultTransitContext`?

2. I have found that `min_decryption_version` was [added in 0.3.0](https://github.com/hashicorp/vault/blob/v0.3.0/website/source/docs/secrets/transit/index.html.md) and `min_decryption_version` was [added in 0.7.3](https://github.com/hashicorp/vault/blob/v0.7.3/website/source/api/secret/transit/index.html.md#update-key-configuration). However I have never found any documentation about `latest_version` since 0.2.0. So it seems that `latest_version` should be removed from `VaultTransitKeyConfiguration` 

What do you think?

https://github.com/gmarziou/spring-vault/commit/c8b51e1ffa34318463166a9576284c98f202a006

**Comment by gmarziou** [comment]
Hello Mark, do you you have any comment on my questions?

Should I create a pull request from my changes?
https://github.com/gmarziou/spring-vault/tree/transit-key-config

**Comment by mp911de** [comment]
Seems that the documentation on `latest_version` diverged between the [quick start](https://www.vaultproject.io/docs/secrets/transit/#quick-start) and the actual [reference documentation](https://www.vaultproject.io/api/secret/transit/index.html#parameters-3).

Submit your pull request, no need to ask whether you should. We can continue the discussion in the PR.

**Comment by gmarziou** [comment]
Sure, I will rebase and submit
