### ISSUE TITLE
Any plans for TOTP operations

### ISSUE THREAD

**Issue by pazvanti** [spring-projects/spring-vault#129]
Vault allows TOTP operations (generating shared secret, QR Code, validating submitted code, etc.), however I could not find such functionality implemented in spring-vault. Are there plans for adding it?

**Comment by mp911de** [comment]
We don't have a schedule for a dedicated TOTP API yet. We should give Vault's TOTP some time to evolve until it gets a stable API. We already came across many API changes for other secret backends that kept us busy with adoption. 

We have a [TOTP sample](https://github.com/mp911de/spring-cloud-vault-config-samples/blob/master/spring-cloud-vault/totp-web/src/main/java/example/totp/TotpController.java) in our examples repository. It doesn't require much to interact with the particular backend.

**Comment by pazvanti** [comment]
Thanks for the replying and for providing the example.

**Comment by mp911de** [comment]
Currently, we do not have any plans for a further extension here.
