### ISSUE TITLE
Add support for skip ssl verifying

### ISSUE THREAD

**Issue by slavniyteo** [spring-projects/spring-vault#130]
It is very useful for development to have an ability to skip ssl certificates verifying.

But I can not find this feature in [docs](http://docs.spring.io/spring-vault/docs/current-SNAPSHOT/reference/html/#vault.client-ssl)

**Comment by mp911de** [comment]
We don't like the idea of disabling SSL verification. Authenticity is an integral part of what SSL provides. You can configure the HTTP client yourself, if you need to tweak SSL setup or simply use plain HTTP.
