### ISSUE TITLE
Add support for Batch Encryption/Decryption APIs

### ISSUE THREAD

**Issue by pravsingh** [spring-projects/spring-vault#137]
Vault supports the batch encryption & decryption services. Which is mostly used to achieve performance.

ref: [Batch Transit Operations](https://www.vaultproject.io/api/secret/transit/index.html#batch_input)

I'm working on these APIs for my use case and when testing is complete will create PR from my fork https://github.com/pravsingh/spring-vault.

Please plan this ticket based on the release schedule.

Thanks.

**Comment by mp911de** [comment]
Spring Vault is currently in the release candidate phase and we shouldn't add any changes that could impact core functionality. Please see our [milestones](https://github.com/spring-projects/spring-vault/milestone/9) for release dates. 

Batch encryption seems not to entirely impact Spring Vault, only the transit API. I'd like to include the change if you want to submit a pull request within the next days.

**Comment by pravsingh** [comment]
thanks for the guidance @mp911de. I'll try to send the PR today.

**Comment by pravsingh** [comment]
created https://github.com/spring-projects/spring-vault/pull/138

**Comment by pravsingh** [comment]
could you please add this ticket to 1.1.0 GA milestone?

**Comment by pravsingh** [comment]
thank you.

**Comment by pravsingh** [comment]
@mp911de,
any proposed date for the next release 1.1.0?
I'm eagerly waiting for the release to utilize the batch APIs in my product.
thanks

**Comment by mp911de** [comment]
Release dates are documented in the milestones: https://github.com/spring-projects/spring-vault/milestones. 1.1.0 GA will ship after the Spring Framework 4.3.12 release.

**Comment by pravsingh** [comment]
awesome. thanks.
