### ISSUE TITLE
Lombok's @Data can reveal secrets if any

### ISSUE THREAD

**Issue by pravsingh** [spring-projects/spring-vault#139]
@Data generates toString() method which includes all the fields of a pojo.
Regardless whether we need it, dumping the pojo will dump any sensitive data in the logs.

Its better to replace
```java
@Data
```
with
```java
@Getter
@Setter
```

**Comment by mp911de** [comment]
We don't use `@Data` on our public API. It's also not the responsibility of this framework to prevent leakage to the logs – enabling debug mode will dump all wire communication to the log, if using Apache Http Client for instance. We already did everything to reduce points of exposure.

**Comment by pravsingh** [comment]
thanks for the clarification.
