### ISSUE TITLE
Support Kubernetes authentication

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#143]
Kubernetes JWT authentication is available since Vault 0.8.3, see https://www.vaultproject.io/docs/auth/kubernetes.html.

**Comment by nikoncode** [comment]
I can try to implement this authentication method if nobody else wants.

**Comment by mp911de** [comment]
Feel free to submit a PR. Along with this ticket we wanted to investigate what's the best approach to obtain a Kubernetes JWT token to improve configurability (fetch the token from some metadata resource, environment, …).

**Comment by christophetd** [comment]
@nikoncode any update? I'm interested by this feature as well, so I might start working on a PR if you didn't get the chance to.

**Comment by mp911de** [comment]
See also #166.
