### ISSUE TITLE
Deprecated path cubbyhole/response

### ISSUE THREAD

**Issue by christophetd** [spring-projects/spring-vault#163]
The path `cubbyhole/response` that Spring Vault calls for cubbyhole authentication seems to be deprecated:

```json
"warnings": [
    "Reading from 'cubbyhole/response' is deprecated. Please use sys/wrapping/unwrap to unwrap responses, as it provides additional security checks and other benefits."
  ]
```
Let me know if a PR for that would be useful.

**Comment by mp911de** [comment]
Cubbyhole was deprecated in Vault 0.6.2, the wrapping endpoint was introduced in that same version. Any change would require raising the Vault baseline to a version equal or above 0.6.2.

We could do that for Spring Vault 2.0.

**Comment by mp911de** [comment]
Reconsidering thing ticket. 0.6.2 was released on 5 Oct 2016, about a year ago. I'm not sure breaking compatibility brings us forward. Let's reschedule this ticket for a time the cubbyhole response unwrapping will undergo changes in Vault.
