### ISSUE TITLE
CubbyholeAuthentication doesn't allow unwrapping of something else than a token

### ISSUE THREAD

**Issue by christophetd** [spring-projects/spring-vault#164]
Hi, 

I'm interested to try out the following workflow, which I think is quite a standard one.

- Each application has a `role_id` in its configuration, as well as a `wrapping_token` that was baked into it at deployment time
- This wrapping token was created for the application to be able to read its `secret_id`, e.g. using `vault write -wrap-ttl=60s -f auth/approle/role/myapp_role/secret-id`
- When the application starts up, it hits `sys/wrapping/unwrap` with its unwrapping token, and gets back its `secret_id` (and raises a security alert if the call fails because the response has already been unwrapped)
- From that (standard AppRole authentication flow), the application uses its `role_id` and `secret_id` to hit  `/auth/approle/login` and get an authentication token

I tried the following configuration:

```java
    @Override
    public ClientAuthentication clientAuthentication() {
        CubbyholeAuthenticationOptions options = CubbyholeAuthenticationOptions.builder()
                .initialToken(VaultToken.of("f8989998-6311-3084-d11f-1247fb87160d"))
                .wrapped()
                .build();

        return new CubbyholeAuthentication(options, restOperations());
    }
```

But it seems that the `CubbyholeAuthentication` strategy doesn't support unwrapping AppRole authentication responses, as Vault's unwrapping response looks like:

```json
{
        ...
	"data": {
		"response": "{\"request_id\":\"8a15abfa-6feb-c569-a8d0-045058dc9c67\",\"lease_id\":\"\",\"renewable\":false,\"lease_duration\":0,\"data\":{\"secret_id\":\"955b92bf-3e51-8aa5-dbfd-17bd7201a84d\",\"secret_id_accessor\":\"2ef56113-4744-a52b-7b88-7a1a80ce0fcd\"},\"wrap_info\":null,\"warnings\":null,\"auth\":null}"
	},
	....
}
``` 

And `CubbyholeAuthentication`'s [`getToken`](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/authentication/CubbyholeAuthentication.java#L262)  method seems to only support retrieving an authentication token (not a secret ID for instance) from the `data.response.auth` field (which is `null` here)

```java
VaultResponse response = VaultResponses.unwrap((String) data.get("response"), VaultResponse.class);
Assert.state(response.getAuth() != null, "Auth field must not be null");
return LoginTokenUtil.from(response.getAuth());
```

I'm unsure whether this behavior is intentional? More generally, it seems that the CubbyHole implementation for authentication only allows to directly unwrap authentication tokens, and not AppRole secret IDs or something else.

Thanks!

**Comment by christophetd** [comment]
The documentation of `CubbyholeAuthentication` states:

> Cubbyhole authentication uses tokens as primary login method

So I guess this behavior is intentional. Any plans to support wrapped AppRole authentication in the future?

**Comment by mp911de** [comment]
`CubbyholeAuthentication` is intended only to unwrap a pre-wrapped token.

We introduced pull mode with #132 (Version 1.1.0) for [`AppRoleAuthentication`](https://docs.spring.io/spring-vault/docs/current/api/org/springframework/vault/authentication/AppRoleAuthentication.html). The implementation is slightly different: The initial token allows reading the `secretId` from `POST auth/approle/role/{role}/secret-id`.

Adding a possibility to read a wrapped `secretId` should be possible, too. Care to submit a pull request against Spring Vault 2.0.x?

**Comment by christophetd** [comment]
Indeed, just came accross `AppRoleAuthentication`'s `initialToken`, but it's a bit different as you describe, it's not really unwrapping.

I'm gonna try to start working on a PR for that. I was thinking of adding a `unwrappingToken` attribute to `AppRoleAuthenticationOptions`, and having `AppRoleAuthentication`'s [`getSecretId`](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/authentication/AppRoleAuthentication.java#L175-L193) call the unwrapping endpoint if this attribute is set.

**Comment by christophetd** [comment]
See #165 for a first PR shoot.
