### ISSUE TITLE
Retain JSON datatypes in PropertySource

### ISSUE THREAD

**Issue by d1d0rn** [spring-projects/spring-vault#169]
We are evaluating switching from cloud config server to using vault for storing yml/json config and one thing we noticed is that all properties come as strings. It doesn't matter when you use @Value or env.getProperty(), but if you don't know the type and just do something generic with PropertySource it is a bit different from config server, which retains original data types coming from json.

The code change is very simple to fix that:

	
     @SuppressWarnings("unchecked")
     private static void flattenElement(String propertyPrefix, Object source,
			Map<String, Object> resultMap) {

		if (source instanceof Iterable) {
			flattenCollection(propertyPrefix, (Iterable<Object>) source, resultMap);
			return;
		}

		if (source instanceof Map) {
			doFlatten(propertyPrefix, ((Map<String, ?>) source).entrySet().iterator(),
					resultMap);
			return;
		}

		resultMap.put(propertyPrefix, source == null ? null : source);
	}

And then updating all dependent declarations. I wonder if there was any specific reason for converting to strings.

Thanks!

**Comment by spencergibb** [comment]
Config server actually returns everything as a string, but when it is appllied to `@ConfigurationProperties` deserialization is done.

**Comment by mp911de** [comment]
@spencergibb would prevent us something from propagating the native type? Or is it just to stay consistent across all Spring Cloud Config integrations?

**Comment by d1d0rn** [comment]
@spencergibb to better illustrate where i see the difference in behaviour, this is our code below. I'm not sure it is the best way to achieve what we need, but the idea is basically to pull sets of properties starting with specific prefixes and merge some of them together (e.g. i have a "default" prefix and a "test1" one for specific client. i don't want to repeat bunch of properties shared between clients for each client, so i first read "default" ones and then put "test1" on top/merge):

    @Autowired
	Environment env;
	
	@Override
	public void afterPropertiesSet() throws Exception {
		Map<String, Object> map = getPropertiesStartingWith((ConfigurableEnvironment)env, "clients.");
	}

	public static Map<String, Object> getPropertiesStartingWith(ConfigurableEnvironment aEnv, String aKeyPrefix) {
		Map<String, Object> map = getAllProperties(aEnv);
	}

	public static Map<String, Object> getAllProperties(ConfigurableEnvironment aEnv) {
		Map<String, Object> result = new HashMap<>();
		aEnv.getPropertySources().forEach(ps -> addAll(result, getAllProperties(ps)));
		return result;
	}

	public static Map<String, Object> getAllProperties(PropertySource<?> aPropSource) {
		Map<String, Object> result = new HashMap<>();

		if (aPropSource instanceof CompositePropertySource) {
			CompositePropertySource cps = (CompositePropertySource) aPropSource;
			cps.getPropertySources().forEach(ps -> addAll(result, getAllProperties(ps)));
			return result;
		}

		if (aPropSource instanceof EnumerablePropertySource<?>) {
			EnumerablePropertySource<?> ps = (EnumerablePropertySource<?>) aPropSource;
			Arrays.asList(ps.getPropertyNames()).forEach(key -> result.put(key, ps.getProperty(key)));
			return result;
		}

		return result;
	}

**Comment by mp911de** [comment]
I've changed this ticket to retain data types without conversion to `String`. That's in place now.
