### ISSUE TITLE
Return Mono<VaultResponse> for ReactiveVaultOperations#write()

### ISSUE THREAD

**Issue by Trundle** [spring-projects/spring-vault#177]
Hi,

First of all, thank you for all the work you put into spring-vault.

I might be missing something, but is there a specific reason why `ReactiveVaultOperations` returns a `Mono<Void>` for the write operation instead of a `Mono<VaultResponse>`? The blocking write method in `VaultOperations` returns a `VaultResponse`.  I have some troubles imaging how one would write a reactive version of `VaultTransitOperations` without having access to the write operation's response.

Cheers,
Andy

**Comment by mp911de** [comment]
Good catch and thanks for using Spring Vault and the early feedback, really appreciate it. This is a bug.

**Comment by mp911de** [comment]
That's fixed now.
