### ISSUE TITLE
RoleId and SecretID in AppRoleAuthenticationOptions not visible

### ISSUE THREAD

**Issue by dennis-dai** [spring-projects/spring-vault#179]
I was trying out the sample code for AppRole authentication from the documentation and both RoleId and SecretID cannot be resolved. Looking at the source code and they are both inner interfaces of the `AppRoleAuthenticationOptions` class without `public`/`protected` keyword. Should the `public`/`protected` keyword be added?

Thanks,
Dennis

**Comment by dennis-dai** [comment]
Forgot to add that this is for the 2.0.0.RC1 release.

**Comment by mp911de** [comment]
Good catch. Thanks for trying out a milestone build.

**Comment by lonngshao** [comment]
sorry my english is bad 。the problem in version 2.0.0.RC1 may still exits  。 Looking at the source code and they are both inner interfaces of the  AppRoleAuthenticationOptions 。 RoleId and SecretID 's  modifiers are " static abstract"

**Comment by dennis-dai** [comment]
RC1 is already tagged so the fix won't go in there. You can either grab the snapshot or fork the repo and put the fix in yourself, until Mark can tag another release.
