### ISSUE TITLE
[Help Wanted] Why is SslConfiguration needed when used with Apache's HttpComponents?

### ISSUE THREAD

**Issue by danielmihai** [spring-projects/spring-vault#180]
Hi all, 

I have a SpringBootApplication in which I specified ComponentScan annotation to include the VaultConfiguration package. This Application uses Apache's HttpComponents to make calls somewhere. I specified in the VaultConfiguration to use SslConfiguration.NONE. When I run maven clean install, I get the following error in the module i'm interested to use (Spring) Vault. 

```java
 o.s.b.a.l.AutoConfigurationReportLoggingInitializer - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-12-02 04:41:36 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vaultTemplate' defined in class path resource [com/oracle/athena/vault/VaultConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.vault.core.VaultTemplate]: Factory method 'vaultTemplate' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientHttpRequestFactoryWrapper' defined in class path resource [com/oracle/athena/vault/VaultConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.vault.config.AbstractVaultConfiguration$ClientFactoryWrapper]: Factory method 'clientHttpRequestFactoryWrapper' threw exception; nested exception is org.apache.http.ssl.SSLInitializationException: class configured for SSLContext: sun.security.ssl.SSLContextImpl$TLSContext not a SSLContext
``` 
Why am I obliged to specify a certain keyStore (keyStore because I'm the client connecting to the Vault) and how can I surpass this specification? 

Any help or direction to solve this is much appreciated. 

Thanks,
Daniel.

**Comment by mp911de** [comment]
Hey Daniel, the message does not look like any regular SSL/TLS configuration error.

Can you provide a bit more context (JDK version used, a minimal bit of code to reproduce the issue). Usually, this kind of issue arises from class loader issues (e.g. using PowerMock for mocking static methods and such).

**Comment by danielmihai** [comment]
The Java version is 1.8.0_122. Indeed it arises when the unit tests are run. I'll come back with an example.

**Comment by danielmihai** [comment]
I found a workaround, I don't know if it's recommended to do this. The blog post says to use @PowerMockIgnore to ignore the ssl config error @PowerMockIgnore({"javax.net.ssl.*","javax.security.*"})
http://mathieuhicauber-java.blogspot.co.uk/2013/07/powermock-and-ssl-context.html

What are your thoughts about it ?

**Comment by danielmihai** [comment]
Using @PowerMockIgnore solved my issue for now.

**Comment by mp911de** [comment]
I'm not a PowerMock user. From what I see here is that we cannot do anything for you as your environment is altered in a way that does not cope with the involved components. 

Personally, I'd refrain from in-memory mocks used along with integration tests. Even more from static mocking as it causes effort to track down issues where it becomes clear that it's not an issue of the actual component but your testing setup.
