### ISSUE TITLE
type RoleId and SecretID are not visible  still exsits in version 2.0.0.RC1 #179

### ISSUE THREAD

**Issue by lonngshao** [spring-projects/spring-vault#182]
sorry my english is bad 。the problem in version 2.0.0.RC1 may still exits 。 Looking at the source code and they are both inner interfaces of the AppRoleAuthenticationOptions 。 RoleId and SecretID 's modifiers are " static abstract" #179

**Comment by mp911de** [comment]
Not sure how to port a bugfix to an already released version – 2.0 RC1 was released 22 days ago and the bug was fixed 14 days ago. Closing as the bug was fixed with 7244973befc2463ac703484b3331363475e04a37.
