### ISSUE TITLE
Configuration classes in jar file

### ISSUE THREAD

**Issue by dheerajjoshim** [spring-projects/spring-vault#188]
This is not really an issue in spring-vault. 
I am trying to use spring-vault in our project and I have added vaultConfiguration class

```
@Configuration
@Profile("!Developer")
public class VaultConfiguration extends AbstractVaultConfiguration {
    //Method implementation
}
```
For developers day to day activities they need not to use vault directly and I am planning to give a simple database based API to store secrets. However in production we want to use vault. To do so I have added "Developer" profile and added @Profile for VaultConfiguration classes. However during start up AbstractVaultConfiguration with @Configuration annotation still tries to load. Creating 

> A component required a bean named 'secretLeaseContainer' that could not be found.

Is there a way I can apply profile to super classes inside a jar ?

**Comment by mp911de** [comment]
You have somewhere a component that requires `secretLeaseContainer`. Adding `@Profile` entirely disables the configuration class.

**Comment by dheerajjoshim** [comment]
I have just this configuration class in entire project. No other vault related code or components

**Comment by mp911de** [comment]
I'm not able to reproduce the issue. Please provide a reproducer.

```java
public class DemoApplication {

	public static void main(String[] args) {

		System.setProperty("spring.profiles.active", "Development");
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(VaultConfiguration.class);

		context.start();

		System.out.println(Arrays.toString(context.getBeanNamesForType(SecretLeaseContainer.class)));

		context.stop();
	}

	@Configuration
	@Profile("!Development")
	public static class VaultConfiguration extends AbstractVaultConfiguration {

		public VaultEndpoint vaultEndpoint() {
			return VaultEndpoint.create("localhost", 8080);
		}

		public ClientAuthentication clientAuthentication() {
			return new TokenAuthentication("foo");
		}
	}
}
```

resulting in

```
Jan 23, 2018 9:16:05 AM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFORMATION: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3d646c37: startup date [Tue Jan 23 09:16:05 CET 2018]; root of context hierarchy
[]
```

**Comment by dheerajjoshim** [comment]
Ok. You can close this ticket. I had an assert Statement in some test code which was causing this problem.
I had to do a grep to find it out.
Thanks (Y)
