### ISSUE TITLE
Profile based @VaultPropertySource

### ISSUE THREAD

**Issue by dheerajjoshim** [spring-projects/spring-vault#193]
This is more of a spring question but since I am having it while using spring vault, I will ask it here.
We use spring vault in our application and we use vault only in production, developers get a developer profile which stores their data in db.

Now I want to use @VaultPropertySource to add property source to environment
`@VaultPropertySource(value = "secret/myapp")`

Can this annotation be made profile specific? where only production mode would use it, but developer profile would use something else? Any pointers on how to achieve this?

**Comment by mp911de** [comment]
What have you tried so far? Have you tried using `@VaultPropertySource` with a `@Configuration` that is activated by `@Profile`?

**Comment by dheerajjoshim** [comment]
I have tried it. And `@VaultPropertySource` works fine with production Profile. And I am able to inject items from vault using `@Value("${myapp.supersecret}")`
But when its developer profile. I don't get all these values because vault is not contacted at all.

And we have many `@Configuration` classes

**Comment by mp911de** [comment]
Sounds to me as you need to properly design/cut your profiles for dev and production. This isn't something Spring Vault can really help.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
