### ISSUE TITLE
Getting Started and Dependencies

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-vault#20]
The current [Getting Started](http://docs.spring.io/spring-vault/docs/1.0.0.BUILD-SNAPSHOT/reference/html/#vault.core.getting-started) documentation states the dependencies necessary are:

```xml
<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.vault</groupId>
    <artifactId>spring-vault-core</artifactId>
    <version>{version}</version>
  </dependency>

</dependencies>

```

I found that in order to run the simple application, I need the following:

```xml
<dependencies>
	<dependency>
		<groupId>org.springframework.vault</groupId>
		<artifactId>spring-vault-core</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-beans</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-web</artifactId>
	</dependency>
	<dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-databind</artifactId>
	</dependency>
	<dependency>
		<groupId>commons-logging</groupId>
		<artifactId>commons-logging</artifactId>
		<version>1.2</version>
	</dependency>
</dependencies>
```

It might be nice to bring in these dependencies transitively. If not, then it would at least be nice to include the necessary jars in the docs

**Comment by mp911de** [comment]
Not quite sure why these dependencies weren't pulled in transitively as they are compile scoped. I suspect the mentioned milestone repo as it worked with Gradle/Maven once the Snapshots repo got referenced.

**Comment by rwinch** [comment]
@mp911de It looks like forcing an update on the SNAPSHOT repository fixed it for me. I'm not sure how I got a bad version cached locally.
