### ISSUE TITLE
VaultSysTemplate.getPolicyName should not throw an exception for not found policies

### ISSUE THREAD

**Issue by mikebell90** [spring-projects/spring-vault#202]
If you call on a policy that doesn't exist, what actually happens is the RestOperation sees a non 200 and throws a VaultException. This isn't super helpful because VaultException is mostly not subclassed, so other than parsing strings (a no no), it's not possible to tell if you failed because
a) of rights
b) of some IO connection issue
c) of vault server failure)
d) of not found.

I'll open a different ticket on VaultException, but the reason I asked this question is it's not clear this was the original intent, since the code basically 
- calls the restOperation
- checks for 404 and returns null.

The second part never executes due to the VaultException

**Comment by mp911de** [comment]
`VaultSysTemplate.getPolicy(…)` should not throw an exception if the policy is not found. That's a bug on our side.
