### ISSUE TITLE
Provide a richer subclass strata of VaultException

### ISSUE THREAD

**Issue by mikebell90** [spring-projects/spring-vault#203]
For example

VaultException
- VaultLocalException
- VaultRemoteException
   - VaultHttpException (includes Http code)

**Comment by mikebell90** [comment]
Under VaultHttpException
- VaultAuthorizationException (403)
- VaultServerException (5xx)
- VaultBadRequestException (4xx)

**Comment by mp911de** [comment]
Thanks for raising this issue. It makes sense to revisit our exception hierarchy to provide some more guidance.

**Comment by mikebell90** [comment]
Great. LMK if a PR to start the design process is something you'd like

**Comment by mikebell90** [comment]
Thanks. to clarify, the issue is a lot of info is hidden in the translation from HttpRestExceptions (or whatever that class is) to VaultException. Ideally we'd know exactly what error occurred
- can't connect to vault server
- authentication/authorization errors
- bad endpoint
- error parsing json
- etc

**Comment by mp911de** [comment]
Thanks a lot for your great dedication to Spring Vault.

Let's start with the simple things first and see how we progress from there. I'd propose to look at all places where we deal with exceptions today. The usual pattern is to have an `ExceptionTranslator` for upstream exception conversion (e.g. [`PersistenceExceptionTranslator`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/support/PersistenceExceptionTranslator.html) for persistence-related exceptions), in the `core` package.

From what I see right now for the HTTP interaction, having a `VaultClientException` and a `VaultHttpStatusException` (both in the `client` package) should be sufficient for the start. Creating more types (to reflect specific status codes) would be an overkill for the start.

A pull request would be fantastic to continue the discussion there.

Does this make sense?

**Comment by mikebell90** [comment]
Yeah, it does. I'll take a look at it.

**Comment by mikebell90** [comment]
I'm starting to look at this today.

**Comment by mikebell90** [comment]
See #216

**Comment by mp911de** [comment]
Closed #216 as per https://github.com/spring-projects/spring-vault/pull/216#issuecomment-379770766.

**Comment by mp911de** [comment]
Closing this ticket as we improve on exceptions on the go.
