### ISSUE TITLE
Since Java 8 is required, consider for future release using Optional instead of null

### ISSUE THREAD

**Issue by mikebell90** [spring-projects/spring-vault#205]
in return values.

Thanks!

**Comment by mp911de** [comment]
This isn't going to happen. 

`Optional` is basically a wrapper around `null` values that creates overhead to some degree and doesn't solve nullability in the first place. The API has still to deal with nullability in the sense to decide which optional to return. Calling code, that isn't benefiting from `Optional` (which is a considerable amount of code out there) has to deal with a clunky API for the sake of unwrapping values that ends up quite often with `orElse(null)`.

`Optional` is a great tool for functional approaches or when used in combination with streaming.
