### ISSUE TITLE
Introduce VaultWrappingTemplate to abstract wrapping operations

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#208]
We should provide `VaultWrappingTemplate` to encapsulate calls to `/sys/wrapping` for response unwrapping/lookup/rewrap and wrapping.

**Comment by mikebell90** [comment]
Could you elucidate further what you meant? Are you proposing
- VaultWrappingTemplate is a subclass of VaultTemplate but adds wrapping and unwrapping operations?
- VaultWrappingTemplate only includes these operations?

Not sure why we don't just expose the unwrap and wrap ops in opsForSys?

**Comment by mikebell90** [comment]
Actually originally I was just suggesting VaultTokenRequest had the x-wrap-ttl or whatever it is as an option in the builder

**Comment by mp911de** [comment]
It's the latter one, add a dedicated operations interface for wrapping operations. Exposing an interface is one part, the other one is where we mount that one. Providing overrides for all API methods to wrap responses creates a lot of noise and a ton of additional methods as they require different return types and probably different names.

Wrapping is now a first-class citizen and I see why it was put under sys. I'd keep it on the top level as it's not really tied to the typical sys operations (rekeying, sealing, …).

Regarding 
> VaultTokenRequest had the x-wrap-ttl

see  my https://github.com/spring-projects/spring-vault/issues/201#issuecomment-369941506:

> Regarding the second item, wrapped token creation: Feel free to submit a pull request for wrapped regular/orphan token creation. On a related note, we could introduce VaultWrappingTemplate since wrapping is becoming more and more a first-class citizen with Vault. I filed #208 for that purpose.
