### ISSUE TITLE
VaultOperations and Passivity

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-vault#21]
Given we cannot control the vault API, how would we add additional functionality to `VaultOperations` and remain passive?

**Comment by spencergibb** [comment]
How to we do it for something like redis?

**Comment by mp911de** [comment]
Redis is one of the data stores that requires active client development. The number of clients providing a generic API (invoking a generic command) increases but Redis is still a pain. 

`VaultTemplate` exposes callback methods (within a Session context and without). Both methods accept callback objects that are called with either `VaultSession` or `VaultClient`. `VaultSession` and `VaultClient` expose methods for HTTP `PUT`/`POST`/`GET`/`DELETE` interaction and a `exchange` method (inspired by `RestTemplate`).

**Within a Vault Session**
```java
vaultOperations.doWithVault(new SessionCallback<Object>() {
			@Override
			public Object doWithVault(VaultSession session) {

				session.postForEntity()/putForEntity()/...
				return …;
			}
		})
```
**Without a Vault Session**
```java
vaultOperations.doWithVault(new ClientCallback<Object>() {
			@Override
			public Object doWithVault(VaultClient client) {
				
				client.getForEntity()/client.postForEntity()/…
				return …;
			}
		});
```

**Comment by mp911de** [comment]
Closing this question as we're using now `RestTemplate` so users are able to interact with Vault's HTTP API within a session/outside a session.
