### ISSUE TITLE
Add Spring's versions compatibility on documentation

### ISSUE THREAD

**Issue by abnerrolim** [spring-projects/spring-vault#211]
Couldn't  migrate from 1.0.1.RELEASE to 2.0.0.RELEASE because last release introduce a dependency from Spring 5.x.x versions. Can't find any topic about compatibility.
The dependency (at least that one I found) is org.springframework.web.util.UriBuilderFactory that's not exists on  4.3.12.RELEASE API I'm using.

**Comment by mp911de** [comment]
Spring Vault 2.x requires Spring Framework 5. We mention the [required version in the reference docs](https://docs.spring.io/spring-vault/docs/current/reference/html/#requirements) and ship with a [changelog](https://docs.spring.io/spring-vault/docs/current/changelog.txt) on each release that contains all tickets and dependency upgrades.

**Comment by abnerrolim** [comment]
Sorry, my fault, only read the github stuff.
