### ISSUE TITLE
Does Spring Vault understand reAuth?

### ISSUE THREAD

**Issue by mikebell90** [spring-projects/spring-vault#217]
Let me clarify my question.

Say you use AppRole. You might get back a token. It might be renewable for a time or periodic (renewable for a long time!), but someone might want to simply call the authenticator again, since secretID might not have expired, if the token expires, to get a new token.

A quick glance at SessionLifeCycleManager implied to me this doesn't work currently?

**Comment by mikebell90** [comment]
Translation of above: Shouldn't the SessionManager try to use ClientAuthentication to get a new token if token can't be renewed.

**Comment by mp911de** [comment]
That's happening indirectly. Tokens that fail to renew are reset in `LifecycleAwareSessionManager.renewToken()`/`ReactiveLifecycleAwareSessionManager`. The next request to Vault will initiate a new authentication. Session managers work in a lazy fashion.

**Comment by mp911de** [comment]
Maybe related to #222. Closing this one as it doesn't seem that we can do anything more here.

**Comment by mikebell90** [comment]
Yes it looks like you handled that one
