### ISSUE TITLE
Documentation "Registering a Vault instance using Java based metadata" vs "Instantiating VaultTemplate"

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-vault#22]
It would be nice if [Registering a Vault instance using Java based metadata](http://docs.spring.io/spring-vault/docs/1.0.0.BUILD-SNAPSHOT/reference/html/#vault.core.vault-java-config) discussed how it is different than [Instantiating VaultTemplate](http://docs.spring.io/spring-vault/docs/1.0.0.BUILD-SNAPSHOT/reference/html/#vault.core.template.instantiating). At the moment, I don't feel like this transitions as well as the rest of the documentation.

**Comment by mp911de** [comment]
Fixed with aa4661b.
