### ISSUE TITLE
Client sending Vault an expired token resulting in failures of all Vault calls

### ISSUE THREAD

**Issue by jampearl36** [spring-projects/spring-vault#222]
We are seeing a situation where after the login token renewal fails because of a Connect Timeout exception (see below for more details), every subsequent call to Vault is returning a 403 possibly because the expired token is being passed to Vault.

I was looking at `LifecycleAwareSessionManager` class and noticed that a new `login()` is forced only on a `null` token or when the client **can** connect to the server and receives an appropriate http 4XX exception (in the renewal flow).

But what about the case where the client was **not** able to connect to the Vault server because of a connect timeout (in the async thread) so the token is not explicitly set to null and the renewal flow is never hit.

I believe since the renewal flow is never hit or a new login is not forced, the vault spring client in our case is hitting Vault with the expired token and getting the 403s.

Shouldn't the login token be reset for all kinds of exceptions to force a new login for subsequent Vault requests?

We are on 1.1.1.RELEASE.

Question on stackoverflow - https://stackoverflow.com/questions/48914774/expired-login-token-refresh-lifecycleawaresessionmanager

Logs

```json
{
"message": "Cannot renew VaultToken",
"logger_name": "org.springframework.vault.authentication.LifecycleAwareSessionManager",
"thread_name": "spring-vault-ThreadPoolTaskScheduler-1",
"stack_trace": "org.springframework.vault.VaultException: Cannot refresh token; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on POST request for \"https://<server>:<port>/v1/auth/token/renew-self\": Connect to <server>:<port>  failed: connect timed out; nested exception is org.apache.http.conn.ConnectTimeoutException
connect timed out\n\tat org.springframework.vault.authentication.LifecycleAwareSessionManager.renewToken(LifecycleAwareSessionManager.java:209)\n\tat org.springframework.vault.authentication.LifecycleAwareSessionManager$1.run(LifecycleAwareSessionManager.java:261)"
}
```

**Comment by mp911de** [comment]
Thanks for reporting the issue. Currently, the token is left in place and subsequent renewal never happens. Assuming that renewal should happen right before TTL expires, we could consider the token expired and reset for subsequent Vault requests to re-login.

The alternative would be keeping the token (as it is right now) and only re-schedule renewal which could lead more often to using an expired token.

Dropping the token seems to me the way to go – as you already mentioned.
