### ISSUE TITLE
Batch decryption fails if plaintext is empty

### ISSUE THREAD

**Issue by mikkokoli** [spring-projects/spring-vault#223]
I have a bunch of ciphertexts I need to decrypt in a batch for performance reasons. Some of the ciphertexts decrypt into an empty string. 

Trying to do this with `TransitOperations` fails. It tries to create a Plaintext, but `Plaintext.of()` expects a non empty string.

In my opinion `Plaintext.of()` should accept an empty string. Vault itself will happily accept empty strings for the plaintext.

**Comment by mp911de** [comment]
We should align to what Vault does. It may make sense for security reasons to encrypt empty values (see #1874).

**Comment by mp911de** [comment]
I reopened this one to fix the subsequent issue. Feel free to submit a pull request.
