### ISSUE TITLE
Extend VaultPkiTemplate with generateRoot(…) and createRole(…)

### ISSUE THREAD

**Issue by khos2ow** [spring-projects/spring-vault#224]
I have this use case to generate root CA, configure the URLs and create role programmatically and then issue a certificate against it. So at any given point `pki/foo-uuid/...`, `pki/bar-uuid/...` may or may not exist while issuing certificate is executed. According to official Vault [guide](https://www.vaultproject.io/docs/secrets/pki/index.html#setup) the workflow is as follow:

1. check if PKI mount point exists, if not, mount it `VaultSysTemplate.mount`
2. check if root CA exists, if not, create it (currently missing)
3. update config urls (currently missing)
4. check if role exists, if not, create it (currently missing)
5. issue a certificate `VaultPkiTemplate.issueCertificate`

I've managed to work around it by calling `vaultOperations.write` for the missing API calls (the same can be found in integration tests). So my question is, was there a specific reason those API methods (e.g. `VaultPkiTemplate.generateRoot(type)` or `VaultPkiTemplate.createRole`) hasn't been implemented?

**Comment by mp911de** [comment]
We're implementing support for most common use-cases first. Until now, no one asked for `generateRoot(…)` to support. Keep in mind that Vault provides a ton of API calls. Looking at role creation, it accepts 31 parameters right now and the number of parameters keeps growing over time.

That being said, we can observe that we will likely be always behind what Vault provides and we don't want to constantly change our API objects. Using `VaultOperations.write(…)` is perfectly fine as this method provides you full access with full flexibility to API calls within a managed session.

We might consider coming back to extended PKI support once things have settled.

**Comment by khos2ow** [comment]
I see your point, thanks for the explanation. Let me know when you want to circle back on this, I might be able to help with the PR.
