### ISSUE TITLE
Get added to Spring IO Platform

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-vault#23]
We should ensure that spring-vault is part of Spring IO Platform so that projects part of the platform can rely on it. See http://docs.spring.io/platform/docs/current/reference/htmlsingle/#maintenance-adding-dependencies

**Comment by mp911de** [comment]
Earliest integration with Spring IO Platform could be with Cairo, based on Spring Framework 5 and Spring Boot 2.0.

**Comment by wilkinsona** [comment]
I haven't heard of any projects in the Platform wanting to depend on Spring Vault so I don't think there's any need to rush here. Also, depending on the outcome of https://github.com/spring-projects/spring-boot/issues/8779, it may not be necessary to add Vault to the Platform itself as it might come in via Boot anyway.

**Comment by mp911de** [comment]
Spring IO Platform is EOL so closing this one.
