### ISSUE TITLE
SLF4J vs commons-logging?

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-vault#24]
Is it intentional to use SLF4J as apposed to commons-logging (as Spring Framework does)? If it is, this doesn't seem ideal given the framework uses commons-logging. We should probably also update the dependencies for #20 to have slf4j an implementation and switch to `jcl-over-slf4j`

**Comment by mp911de** [comment]
We used SLF4J in Spring Cloud Vault and so it was retained. Spring Vault isn't very demanding regarding logging so aligning with Spring Framework by using commons-logging seems like natural fit.
