### ISSUE TITLE
Add @VaultPropertySource support for versioned Key-Value backend

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#245]
Spring Vault is not usable with Vault's versioned Key/Value backend introduced with 0.10.0. The versioned backend is enabled by default which adds another level of severity. 

The versioned Key/Value backend entirely changed its API (nested responses, e.g. `{data: { data: { here comes the actual payload }}`, changed API paths e.g. `secret/data/secret-name` instead of `secret/secret-name`). It is possible to read from `…/data/…` paths but referencing secrets requires a `${data.…}` prefix to unwrap nesting.

Using the Key/Value backend allows a uniform API even if versioning is disabled by setting an HTTP header (`X-Vault-Kv-Client: v2`) but the client has to be aware it's reading from a key-value backend. 

Using a newer format (paths, unwrapping) breaks compatibility with older Vault versions and isn't really a good option for `@VaultPropertySource(…)`.

**Comment by mp911de** [comment]
A possible approach could be introducing `@VersionedVaultPropertySource` to indicate the versioned nature of the underlying backend. A new annotation would give us the possibility to express version-specific attributes and drop renewal. The versioned backend does not support cache timeouts through the TTL property.

**Comment by mp911de** [comment]
Versioned key-value secret backend usage comes with a multitude of usage strategies (here's a list to name some):

* Pin to a specific version
* Select a specific version during runtime
* Use time-based caching and pick a version of a secret
* Apply caching based on a user-defined TTL

Expressing just some of the options would require a very broad annotation with possibly mutually exclusive configuration options. Therefore, we should not introduce such a possibility now.

We could introduce path and mount inspection, similar to how `vault-cli` behaves. We can ask an internal API (`sys/internal/ui/mounts`) to obtain the mount path and mount options.
The mount info gives insight whether the path belongs to a versioned key-value backend. Based on this information, we can rewrite the request path and unwrap the payload.

It would work with today's `@VaultProperties` annotation. The change would not require adding the `data/` path segment in the annotation declaration and so path declarations can be retained. 

A side effect is that an application can declare the path independently from the mount that is available on the server (e.g., use non-versioned in one environment and a versioned backend in another one without the need to change the code).

**Comment by imsatyam** [comment]
@mp911de  I did find VaultVersionedKeyValueTemplate.java in 2.1.2.RELEASE. However, it does not seem to be working with @Import(EnvironmentVaultConfiguration.class). Do we have any example on how to use versioned KV store with  EnvironmentVaultConfiguration?

My apologies for comment on a closed thread. However, this appeared to be the right thread to ask this question.

**Comment by mp911de** [comment]
Via VaultTemplate. You cannot inject VaultVersionedKeyValueTemplate as it requires a Vault path to operate on.

**Comment by imsatyam** [comment]
@mp911de  Thanks for the quick reply Mark. Here is the problem I am facing.

My kv store is of version2 type.
My code to read properties is as under.  It is reading data correctly but in version 1 format.

`vault.sources=secret/data/abcd,secret/data/pqrs` is the config provided for reading secrets.

```import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.MutablePropertySources;
import org.springframework.vault.authentication.ClientAuthentication;
import org.springframework.vault.authentication.TokenAuthentication;
import org.springframework.vault.client.VaultEndpoint;
import org.springframework.vault.config.AbstractVaultConfiguration;
import org.springframework.vault.core.VaultTemplate;
import org.springframework.vault.core.env.VaultPropertySource;

import javax.annotation.PostConstruct;
import java.net.URI;
import java.util.List;

@Configuration
@PropertySource("vault.properties")
public class AppConfig extends AbstractVaultConfiguration {

    @Value("${vault.uri}")
    private URI vaultUri;

    @Value("${vault.token}")
    private String token;

    @Value("#{'${vault.sources:}'.split(',')}")
    private List<String> vaultSources;

    @Autowired
    private ConfigurableEnvironment environment;

    @Autowired
    private VaultTemplate vaultTemplate;

    /**
     * Specify an endpoint for connecting to Vault.
     */
    @Override
    public VaultEndpoint vaultEndpoint() {
        return VaultEndpoint.from(vaultUri);
    }

    /**
     * Configure a client authentication.
     * Please consider a more secure authentication method
     * for production use.
     */
    @Override
    public ClientAuthentication clientAuthentication() {
        return new TokenAuthentication(token);
    }

    @PostConstruct
    public void setPropertySource() {
        MutablePropertySources sources = environment.getPropertySources();
        vaultSources.stream().forEach(vs -> {
            sources.addFirst(new VaultPropertySource(vaultTemplate, vs));
        });
    }
}```

If I remove data from path i.e. `vault.sources=secret/abcd,secret/pqrs`, it simply does not connect and throws exception with 403. This means that it must not be using kv v2. 

Can you please help with the change I need to make here to get the properties correctly?

**Comment by mp911de** [comment]
We prefer using GitHub issues for bug reports and feature requests. Please post your question to StackOverflow.

**Comment by imsatyam** [comment]
Thanks. I have posted my question here https://stackoverflow.com/questions/56481031/how-to-make-versioned-kv-store-work-with-vaultpropertysource

**Comment by nov1n** [comment]
Is there any planned support for this feature in the 1.1.x releases that are compatible with Spring 4?

**Comment by mp911de** [comment]
@nov1n No. We typically do not backport features.
