### ISSUE TITLE
Allow spring-vault to read secrets with POST

### ISSUE THREAD

**Issue by joeyslalom** [spring-projects/spring-vault#256]
When generating a dynamic IAM credential with the STS:

https://www.vaultproject.io/api/secret/aws/index.html#generate-iam-with-sts

The API calls for a POST.  

This credential is rotating, so I am using a `LeaseAwareVaultPropertySource` which contains a `SecretLeaseContainer`.  `SecretLeaseContainer.doGetSecrets()` ultimately invokes `restOperations.getForObject()`, which does a HTTP GET request  rather than the POST the API needs.  Is there a way to read this secret with a POST operation?

**Comment by mp911de** [comment]
The only method `SecretLeaseContainer` (`LeaseAwareVaultPropertySource`) is able to use is `GET`. Looking at `POST /aws/sts/:name`, the request accepts additional request parameters (as of now it's `ttl`). We do not have a possibility to associate such request parameters with lease requests.

Typically, this kind of configuration would go into the backend lease configuration. Care to file a ticket in https://github.com/hashicorp/vault's issue tracker to ask for `GET` requests on `/aws/sts/:name`?

For now, you could subclass `SecretLeaseContainer` and override `doGetSecrets` (see https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/core/lease/SecretLeaseContainer.java#L541-L552) so you issue a `POST` request (`VaultOperations.write(…)`) for the AWS STS backend.

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by joeyslalom** [comment]
Hi Mark, unsure what update I can provide? I was able to plead with our infrastructure team to accept a GET to /aws/sts/:name, but otherwise I would overridden SecretLeaseContainer.  But as you note, that is sort of a half-workaround, I can't associate additional request parameters.  Does it make sense to have a new SecretLeaseContainer for this use case?

**Comment by mp911de** [comment]
Have you tried subclassing `SecretLeaseContainer` and overriding `doGetSecrets `? I was hoping to get a feedback whether this approach would work for you. If that would work, I'd close this ticket.

**Comment by mp911de** [comment]
Putting this one on hold as subclassing the preferred approach to customize the method of secret retrieval.
