### ISSUE TITLE
Increase log level on token renewing errors when using CubbyHoleAuthentication

### ISSUE THREAD

**Issue by abnerrolim** [spring-projects/spring-vault#257]
It's not a bug and can be managed with a few configurations, but I actually had a lot of trouble to find this:

I'm using a CubbyHole Authentication in my apps and the environments are containers. Sometimes when the runtime machine is small, the default parameters of REFRESH_PERIOD_BEFORE_EXPIRY (5 seconds) running at the default ThreadPool (with size 1) is not enough to refresh the token before expiration. 
I'm using the CubbyHole Auth flow, so that means irreversible error when the application wants access Vault. I need to re-deploy to allow the Continous Delivery's script to inject the first token.

Was hard to figure out what happened in that specific environment because all 4XX Vault responses on refresh flow are only logged and with DEBUG level (renewToken on LifecycleAwareSessionManager) and refresh of expired tokens will be answered with 403.

Shouldn't be at least WARN specifically on CubbyHole Auth flow? Not sure of that but in this scenario, a refresh fail will completely break the application, LifecycleAwareSessionManager's login will be not possible, and the token will be set as empty.

To resolve that I overrided sessionManager and threadPoolTaskScheduler beans of AbstractVaultConfiguration to make configurable the pool size and the refresh period before expiry. Also I included LifecycleAwareSessionManager as DEBUG level into app's log4j configuration and it's working now.

**Comment by mp911de** [comment]
Thanks a lot for reporting that issue. We plan to improve support on exceptions with #203. Errors during token renewal are reported on `ERROR` level.

See https://github.com/spring-projects/spring-vault/blob/58159fdb14c0bcaf055dc6ada814ead868599c46/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L306-L316

Overriding beans configured by `AbstractVaultConfiguration` is the way to go to adapt these to your needs. Beans exposed by Spring Vault have a ton of configuration options.

What did you wish was done that would have helped you to achieve your desired changes earlier/easier?

**Comment by abnerrolim** [comment]
Nice, will greatly improve the vault errors feedback!

Yeah, I saw this log into scheduleRenewal but what is happening is that 4xx exceptions will not throw on renewToken() method and Vault error response for expired token renews is 403.

The problem is here (see above): the HttpStatusCodeException is being cathed, the token will be empty, log only as debug and returns false on the is4xxClientError case:
https://github.com/spring-projects/spring-vault/blob/58159fdb14c0bcaf055dc6ada814ead868599c46/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L216-L225

So the next scheduleRenewal() silently will not be scheduled, right?

`

**Comment by mp911de** [comment]
> So the next scheduleRenewal() silently will not be scheduled, right?

That's right and logging happens only on `DEBUG` level. I haven't considered this case before. 

I'd propose to introduce another log event that logs on `WARN` if the failure is swallowed and the application attempts to re-login upon the next access. The non-client error-`DEBUG` log would stay for the time being as exceptions are logged in the caller to prevent double-logging.

I'd also add `VaultSessionManagerException` to improve when `renewToken()` is called.
