### ISSUE TITLE
GcpIamAuthenticationOptions should support acting on behalf of a service account 

### ISSUE THREAD

**Issue by mjungsbluth** [spring-projects/spring-vault#261]
The beauty of Google IAM’s signJwt is that users can sign on behalf of the service account. 
Currently the service account email is taken from GoogleCredential which is only correct for local SA keyfiles. A user with the serviceAccountTokenCreator role falls flat.

What needs to be done:
* Make serviceAccountId configurable in the Builder
* Make the projectId configurable as well

When signing the JWT prefer the SA and project id from the builder. If the project id is null for both builder and GoogleCredential, `-` can be used instead.

I can do a PR next week, if interested...

**Comment by mp911de** [comment]
Thanks for proposing an enhancement. Details are derived from `GoogleCredential` and we have a `GoogleCredentialSupplier` that exposes `GoogleCredential` to `GcpIamAuthentication`. When we want to introduce configuration options, we need to be careful to not cause confusion but rather be clear how Spring Vault obtains SA and project id.

`ServiceAccountAccessor` and `ProjectIdAccessor` (each accepting `GoogleCredential`) seem to be a consistent pattern that is in line with `GcpCredentialSupplier`. By default, projectId and SA are derived from `GoogleCredential` to keep things as they work now. Configuring `projectId` and `serviceAccount` would configure objects that statically return the configured value.

Does this make sense?

**Comment by mjungsbluth** [comment]
I think that makes sense and from a user's perspective it is also simple.

Just to be clear, the *Accessor interfaces would for now be only used internally and the builder would expose static settings for SA id and projectId? Or would you also allow users to specify custom instances of these interfaces?

I already did parts of these changes so I could craft a PR...
