### ISSUE TITLE
Update sys/ calls to use newer APIs for vault 0.8+

### ISSUE THREAD

**Issue by baens** [spring-projects/spring-vault#262]
It looks like [Vault 0.8](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#080-august-9th-2017) deprecated some of their sys API end points, especially ones that have to renew them.

Does there need to be a way to configure where the endpoints are, or just update them in place?

**Comment by mp911de** [comment]
The mentioned endpoints are used only in `SecretLeaseContainer` and are not configurable yet. We could introduce a lease accessor/lease endpoint strategy that allows mapping the changes which are bound to versions pre 0.7.3/post 0.8. Right now, we only use `revoke` and `renew` operations.

**Comment by baens** [comment]
Correct the `SecretLeaseContainer` was the specific class I saw that needed to be changed.

Just to make sure I understand, the `SecretLeaseContainer` is the class that handles the renewal of database credentials or other tokens that needed to be renewed periodically correct? Or is there somewhere else that also handles this? (i.e. where does the `LifecycleAwareSessionManager` come into play)

I would love to contribute, are there any examples in this code base of how to apply the strategy pattern in the way you want here?

**Comment by mp911de** [comment]
> Just to make sure I understand, the SecretLeaseContainer is the class that handles the renewal of database credentials.

That's correct.

> where does the `LifecycleAwareSessionManager` come into play and how does it differ from `SecretLeaseContainer`

`LifecycleAwareSessionManager` uses `auth/token/revoke-self` and `auth/token/renew-self` API calls to renew session tokens. These endpoints aren't deprecated so it's safe to leave `LifecycleAwareSessionManager` as-is. `SecretLeaseContainer` obtains secrets from secret backends which can be associated with a lease, hence it's the one place that deals with renewal and revocation of secret leases.

> I would love to contribute

Great to hear.

> are there any examples in this code base of how to apply the strategy pattern in the way you want here?

I think no, there isn't yet code that compares well to what we plan here.

I'd imagine having an interface (`LeaseAccessor`), that declares two methods:
* `revoke(Lease, RestOperationsCallback<Void>)`
* `renew(Lease, RestOperationsCallback<Lease>)`

And then we could declare an enum that implements the interface. The enum would have two items (`SysLease` and `Legacy`, not exactly sure about the name) and each implements its own API access scheme along with paths and request/response handling. This way, we encapsulate the entire endpoint calls within the corresponding method and the endpoint calls do not share details about request/responses.

Does this make sense?

**Comment by mp911de** [comment]
That's in place now. Endpoints can be set on `SecretLeaseContainer` through `LeaseEndpoints.Legacy`/`LeaseEndpoints.SysLeases`.
