### ISSUE TITLE
Issuing PKI certificate with TTL results in Vault error due to number format

### ISSUE THREAD

**Issue by livesinlondon** [spring-projects/spring-vault#263]
With Spring Vault 2.0.1, when requesting a PKI with TTL through VaultPkiOperations, I get an error from Vault because the TTL got serialised into a floating point number, and Vault expects an integer.

Is this a config issue with Jackson, or an actual bug?

**Comment by mp911de** [comment]
That's hard to judge without context. Please provide:

* Used Vault version
* The stack trace

**Comment by livesinlondon** [comment]
Set up Vault 0.10.3 dev server as per [Vault's Getting Started guide](https://www.vaultproject.io/intro/getting-started/dev-server.html), then enable pki as per [docs](https://www.vaultproject.io/docs/secrets/pki/index.html). Set up a Spring vault config project using [initializr](https://start.spring.io/) - Spring Boot 2.0.3. Add bootstrap.properties to resources/:
```
spring.cloud.vault.token=00000000-0000-0000-0000-000000000000 # use actual token from vault output
spring.cloud.vault.scheme=http
```
Add `@Service` class:
```
@Autowired
    private VaultOperations vault;

    public String svc() {
        return vault.opsForPki().issueCertificate("my-role", VaultCertificateRequest.builder().commonName("example.my-website.com").ttl(10L, TimeUnit.MINUTES).build()).getData().toString();
    }
```
Add an `@Test` that calls `svc()`.

Stack trace:
```
org.springframework.vault.VaultException: Status 500: 1 error occurred:

* error converting input map[seconds:600 negative:false nano:0 zero:false units:[SECONDS NANOS]] for field "ttl": invalid input 'map[negative:false nano:0 zero:false units:[SECONDS NANOS] seconds:600]'

	at org.springframework.vault.client.VaultResponses.buildException(VaultResponses.java:63)
	at org.springframework.vault.core.VaultPkiTemplate.lambda$requestCertificate$0(VaultPkiTemplate.java:99)
	at org.springframework.vault.core.VaultTemplate.doWithSession(VaultTemplate.java:307)
	at org.springframework.vault.core.VaultPkiTemplate.requestCertificate(VaultPkiTemplate.java:92)
	at org.springframework.vault.core.VaultPkiTemplate.issueCertificate(VaultPkiTemplate.java:68)
```

It's not exactly the same issue, but it also looks like a serialisation issue...
I'll dig a bit more tomorrow to try and come up with a minimal setup to reproduce the initial issue with the floating point number...

**Comment by mjungsbluth** [comment]
I also have the same issue. 

I think it is caused by VaultClients#createRestemplate() which is just calling `messageConverters.add(new MappingJackson2HttpMessageConverter());`

This in turn enables the SerializationFeature.WRITE_DATES_AS_TIMESTAMPS Feature (true by default)

`new MappingJackson2HttpMessageConverter(Jackson2ObjectMapperBuilder.json().featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS).build())` should alleviate that although this would pass Strings like 'PT24D' to vault. 

Does Vault support ISO 8601 Durations? All the examples use things like '24h'

**Comment by livesinlondon** [comment]
No. (I tried, using `doSessionWith(...) `, casting the `restOperations` to a `RestTemplate` and replacing that Builder with one into which's constructor I passed my own `ObjectMapper`.) Vault seems to assume seconds as default,  unless a time unit postfix like `s`, `m`, or `h` is applied... A little while ago I found a page listing all permissible postfixes, but unfortunately I can't find it anymore...

**Comment by mp911de** [comment]
The bug here is that we replaced a previously field that contained seconds with `Duration` and this failed. We do not assume any Jackson features to be activated but rather a proper conversion out of the box.
