### ISSUE TITLE
Where's the doWithRestTemplate callback method? 

### ISSUE THREAD

**Issue by livesinlondon** [spring-projects/spring-vault#264]
The docs mention in section 7.5 Execution Callbacks a method doWithRestTemplate(...), but a github search for it yields no results. Has it been implemented yet?

**Comment by mp911de** [comment]
Can you point to a link that contains the mentioned `doWithRestTemplate(…)` reference?

**Comment by livesinlondon** [comment]
Looks like I looked at the wrong version (current-SNAPSHOT instead of current) of the docs; apologies.
https://docs.spring.io/spring-vault/docs/current-SNAPSHOT/reference/html/#vault.core.executioncallback

**Comment by mp911de** [comment]
I see. the current snapshot is outdated and wasn't updated since then.

**Comment by mp911de** [comment]
Outdated docs are removed now. Thanks a lot for filing a bug report and helping the OSS community 👍
