### ISSUE TITLE
Vault URL misses slash between "v1" and "auth"

### ISSUE THREAD

**Issue by andrerivas** [spring-projects/spring-vault#265]
We are trying to use Spring Vault 1.1.2. (Also tried with 1.1.3 with the same result.)

In `AwsIamAuthentication.java` the method `createTokenUsingAwsIam()` tries to do a `postForObject` using the path below, with no beginning slash.

```
VaultResponse response = this.vaultRestOperations.postForObject(
					"auth/{mount}/login", login, VaultResponse.class, options.getPath());
```

When stepping through in the debugger the code eventually gets to `VaultClients.java` where the method `toBaseUri` constructs a URI with no ending slash after `v1`.
```
	private static String toBaseUri(VaultEndpoint endpoint) {
		return endpoint.getScheme() + "://" + endpoint.getHost() + ":"
				+ endpoint.getPort() + "/v1";
	}
```

Then also in the debugger I see that the `insertBaseUrl()` method of `springframework.web.util.DefaultUriTemplateHandler` constructs the final URL with the line `String url = this.getBaseUrl() + uriComponents.toUriString();`. 

In my case `this.getBaseUrl()` is "https://mysite.net:1234/v1" and `uriComponents.toUriString()` is "auth/aws-12344567/login", so the full url becomes https://mysite.net:1234/v1auth/aws-12344567/login with no slash between **v1** and **auth**.

This, of course, does not work.

I see that in `createTokenUsingAwsIam()` in `AwsIamAuthentication.java`, `auth/{mount}/login` is hard coded at line 115. And, as noted above, the ending `/v1` without a slash is also hard coded in `VaultClients.java`. I don't see how AwsIamAuthentication can work properly without the slash between v1 and auth.

Should that have a beginning slash like `/auth/{mount}/login` or is there something else I should be looking at?

We are currently using Spring 4.2.0.RELEASE so upgrading to  Spring Vault 2.0.1 is not an easy solution.

**Comment by mp911de** [comment]
Spring Vault uses Spring's `DefaultUriTemplateHandler` to construct the final URL from any given path (relative and absolute paths). We normalize with `PrefixAwareUriTemplateHandler` the path and make sure that we insert exactly one slash if there is none. 

In Spring Framework 4.2, `DefaultUriTemplateHandler.expandInternal(…)` methods are not yet in place, these methods were introduced later. We can change `PrefixAwareUriTemplateHandler` for 1.1.x to override `expand(…)` so Spring Vault will work with earlier Spring Framework versions.

**Comment by mp911de** [comment]
That's fixed now.
