### ISSUE TITLE
Support Signing of GCP JWT without calling the IAM API

### ISSUE THREAD

**Issue by mjungsbluth** [spring-projects/spring-vault#286]
If service account credentials are configured (by providing the key file in GOOGLE_APPLICATION_CREDENTIALS) it should be superfluous to call the IAM API to sign the JWT for Vault login. 
The private key is already available locally and can be used to sign the JWT directly (saving a network roundtrip).

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
