### ISSUE TITLE
AbstractVaultConfiguration overwrites the default task scheduler bean

### ISSUE THREAD

**Issue by metacubed** [spring-projects/spring-vault#308]
I ran into this issue when using the Spring `@Scheduled` annotation. which expects a generic `TaskScheduler` to be available in the application context.

In Spring Vault 2.0.1, the `AbstractVaultConfiguration` contains a bean definition for `ThreadPoolTaskScheduler` configured with vault specific properties (code below).

Since the bean is unqualified, it replaces the default `TaskScheduler` in the application context. Modules which rely on the default task scheduler start using the vault-specific one instead.

This can be solved by adding a qualifier name to the bean inside the Vault Configuration, and specifically autowiring that bean in any Vault-specific functionality.

https://github.com/spring-projects/spring-vault/blob/c725dcff334304082468a183b5a2015afe8e5086/spring-vault-core/src/main/java/org/springframework/vault/config/AbstractVaultConfiguration.java#L147-L157

**Comment by mp911de** [comment]
You can subclass `AbstractVaultConfiguration`, override the `threadPoolTaskScheduler()` method and add `@Bean @Qualifier("…")` to the overriden method. To solve the issue. Alternatively, provide a task scheduler bean named `taskScheduler` to use a specific scheduler when using `@Scheduled`.

**Comment by metacubed** [comment]
@mp911de Mark, thanks for responding. In my question, I did mention the `@Qualifier` workaround.

The default configuration produces the undesirable effect of overwriting the global scheduler bean with a vault-specific thread configuration.

Spring's out of the box configurations should do the "right" thing by default. Adding a vault-specific `@Qualifier` directly to `AbstractVaultConfiguration` would avoid the unwanted side-effect.

**Comment by mp911de** [comment]
Spring configuration does the right thing™ only to some degree. Individual modules do their best to provide a sufficient level of configuration that suits most users needs while trying to not conflict with other functionality in the eco-system. Serious applications should not rely on defaults but rather apply specific configuration where needed.

What we will do, is renaming the beans to indicate they're originating in Vault's configuration as the bean name is currently rather generic.

**Comment by mp911de** [comment]
Closing without fixing as per comment above.

**Comment by metacubed** [comment]
@mp911de, sounds good. Thanks!
