### ISSUE TITLE
Add namespace support

### ISSUE THREAD

**Issue by maxfortun** [spring-projects/spring-vault#316]
Vault now supports namespaces. Need ability to pass the namespace header.
https://www.vaultproject.io/docs/enterprise/namespaces/index.html

**Comment by maxfortun** [comment]
Examples on how to use namespaces can be found here: https://www.vaultproject.io/api/index.html
Search for `namespace`

**Comment by mp911de** [comment]
Thank you. Namespaces are a concept from Vault Enterprise and not the community version which makes it impossible for us to test in an integrative way.

For now, we recommend registering a [`ClientHttpRequestInterceptor`](https://gist.github.com/mp911de/e2480afd4d5d5c27038e2b1b49b30cfa) on `RestTemplate` to associate a namespace for authentication and administrative operations with Vault.

This is, in general, the better approach than touching every single authentication mechanism to associate the namespace with the login token.

Closing #315 as we don't want to introduce the concept of namespaces to each authentication mechanism.

**Comment by maxfortun** [comment]
Thank you for your suggestion!

**Comment by mp911de** [comment]
Closing this one as we're currently not going to add dedicated support for namespaces to Spring Vault.

**Comment by wevanspariveda** [comment]
Curious if there is a snippet available demonstrating registering a ClientHttpRequestInterceptor on RestTemplate?

**Comment by mp911de** [comment]
Sure. Follow the [Gist](https://gist.github.com/mp911de/e2480afd4d5d5c27038e2b1b49b30cfa) link. Spring Vault uses `ClientHttpRequestInterceptor` itself in [`VaultTemplate`](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTemplate.java#L170).

**Comment by sarithareddy** [comment]
This is how my bootstrap.yml is setup. I couldn't find a way to set "X-Vault-Namespace" header. I'm wondering if you have any pointers for me.

spring.application.name: my-server
spring.cloud.vault.reactive.enabled: false
spring.cloud.vault:
    host: vaultserver.com
    port: 80
    scheme: http
    uri: https://vaultserver.com
    connection-timeout: 5000
    read-timeout: 15000
    config:
        order: -10
    authentication: AWS_IAM
    aws-iam:
        role: my-dev
        aws-path: aws

**Comment by jasonmcintosh** [comment]
BTW for anyone else who hits some of these issues... the gist works great UNTIL you have to use a login method in a given namespace.  In that case, when you go to implement AbstractVaultConfiguration, override restOperations method to also do... might be a cleaner way to get this to work, but just remember logins use a different rest template than do operations.

```
  public RestOperations restOperations() {
        RestTemplate restTemplate = VaultClients.createRestTemplate(vaultEndpointProvider(),
                clientHttpRequestFactoryWrapper().getClientHttpRequestFactory());

        restTemplate.getInterceptors().add((request, body, execution) -> {
            request.getHeaders().add("X-Vault-Namespace", nameSpace);
            return execution.execute(request, body);
        });
        return restTemplate;
    }
```

**Comment by Sythog** [comment]
these interceptors work for me only during the login process. they aren't invoked when querying for data hence no namespace is added

**Comment by Sythog** [comment]
@jasonmcintosh it works for me only during the login process. this interceptor isn't invoked when querying for data hence no namespace is added

**Comment by Sythog** [comment]
@jasonmcintosh @mp911de found out what the problem was. I had to override `restOperations()` from `AbstractVaultConfiguration` and both `doCreateRestTemplate` and `doCreateSessionTemplate` from `VaultTemplate` to make them forward namespace

**Comment by mteodori** [comment]
> Sure. Follow the [Gist](https://gist.github.com/mp911de/e2480afd4d5d5c27038e2b1b49b30cfa) link. Spring Vault uses `ClientHttpRequestInterceptor` itself in [`VaultTemplate`](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTemplate.java#L170).

I cannot make this gist code work, the constructor creating the rest template needs to execute before I can set the namespace

**Comment by CharlieReitzel** [comment]
> For now, we recommend registering a [`ClientHttpRequestInterceptor`](https://gist.github.com/mp911de/e2480afd4d5d5c27038e2b1b49b30cfa) on `RestTemplate` to associate a namespace for authentication and administrative operations with Vault.

That is working for login only.  For secret retrieval Spring Vault Core creates its own `RestTemplate` directly using its own implementation of `RestTemplateBuilder`, so I'm not seeing how to inject the interceptor into a `VaultTemplate`.

**Comment by CharlieReitzel** [comment]
I found a simpler way using `RestTemplateCustomizer`:
```
    static final String VAULT_NAMESPACE_DFLT = "foo/bar";

    @Value("${spring.cloud.vault.namespace:" + VAULT_NAMESPACE_DFLT + "}")
    String fooNamespace;

    @Bean
    public RestTemplateCustomizer forwardNamespaces() {
        log.info("forwardNamespaces - namespace: {}", fooNamespace);
        return (restTemplate) -> {
            log.info("customize - namespace: {}", fooNamespace);
            restTemplate.getInterceptors().add( VaultClients.createNamespaceInterceptor(fooNamespace) );
        };
    }
```

**Comment by oabasov-lohika-tix** [comment]
Maybe it will be helpful for someone
> but just remember logins use a different rest template than do operations.
To do it once for both auth login and for actual vault requests - implement AbstractVaultConfiguration and override 
 restTemplateBuilder method by putting an additional default header.

```
companion object: KLogging() {
        const val VAULT_NAMESPACE_HEADER = "X-Vault-Namespace"
}

override fun restTemplateBuilder(
        endpointProvider: VaultEndpointProvider,
        requestFactory: ClientHttpRequestFactory
    ): RestTemplateBuilder {
        return RestTemplateBuilder.builder()
            .endpointProvider(endpointProvider)
            .requestFactory(requestFactory)
            .defaultHeader(VAULT_NAMESPACE_HEADER, vaultProperties.namespace!!)
    }
```

**Comment by MartinTopchyan** [comment]
> @jasonmcintosh @mp911de found out what the problem was. I had to override `restOperations()` from `AbstractVaultConfiguration` and both `doCreateRestTemplate` and `doCreateSessionTemplate` from `VaultTemplate` to make them forward namespace

Can you please share your example of overriding Vaulttemplate methods?

**Comment by MartinTopchyan** [comment]
> > @jasonmcintosh @mp911de found out what the problem was. I had to override `restOperations()` from `AbstractVaultConfiguration` and both `doCreateRestTemplate` and `doCreateSessionTemplate` from `VaultTemplate` to make them forward namespace
> 
> Can you please share your example of overriding Vaulttemplate methods?

Manage to run.

thanks to @oabasov-lohika-tix
