### ISSUE TITLE
Secret Rotation Failure

### ISSUE THREAD

**Issue by kyleclark71** [spring-projects/spring-vault#321]
Hello,

I've ran into an issue that results in a failure to rotate secrets at the end of their lease. The renewal process is working correctly (renewing the lease until the max-ttl has been reached), but once the lease has reached it's end, the system fails to rotate the secret.

I've tried with a number of default/lease max TTLs to verify if the issue was due to the low TTL times, but I get the same result with small or large TTL values

Vault version: 0.11
spring-vault-core version: 1.1.2.RELEASE
RequestedSecret.Mode: ROTATE
Vault Backend: Database
Default lease TTL: 2m
Max Lease TTL: 3m

I traced the error back a few levels and found the following code. I've annotated the method with comments related to this issue with // ISSUE.
When reading through this code, it appears that this situation was meant to be handled by the first catch block notated below, but that block is no longer catching exceptions related to lease expiration.
```
public class SecretLeaseContainer
    ...
    protected Lease doRenewLease(RequestedSecret requestedSecret, Lease lease) {
        try {
            Lease renewed = lease.hasLeaseId() ? this.renew(lease) : lease;
            if (renewed.hasLeaseId() && renewed.getLeaseDuration() != 0L && renewed.getLeaseDuration() >= (long)this.minRenewalSeconds) {
                return renewed;
            }

            this.onLeaseExpired(requestedSecret, lease);
            return Lease.none();
        } catch (HttpStatusCodeException var4) {
            // ISSUE It appears a 400 error (lease not found or not renewable) is supposed to be handled here
            if (var4.getStatusCode() == HttpStatus.BAD_REQUEST) {
                this.onLeaseExpired(requestedSecret, lease);
            }

            this.onError(requestedSecret, lease, new VaultException(String.format("Cannot renew lease: %s", VaultResponses.getError(var4.getResponseBodyAsString()))));
        } catch (RuntimeException var5) {   
            // ISSUE 400 Error (lease not found or not renewable) is caught here as a VaultException, & no rotation is attempted
            this.onError(requestedSecret, lease, var5);
        }

        return Lease.none();
    }
    ...
}
```

The exception for the 400 Error (lease not found or not renewable) is thrown from here:
```
public abstract class VaultResponses {
    ...
    public static VaultException buildException(HttpStatusCodeException e) {
        Assert.notNull(e, "HttpStatusCodeException must not be null");
        String message = getError(e.getResponseBodyAsString());
        return StringUtils.hasText(message) ? new VaultException(String.format("Status %s: %s", e.getStatusCode(), message)) : new VaultException(String.format("Status %s", e.getStatusCode()));
    }
    ...
}
```

**Comment by mp911de** [comment]
This issue sounds a bit as if it's related to #319. Can you retest using version `2.1.1.BUILD-SNAPSHOT`?

**Comment by kyleclark71** [comment]
Unfortunately our project is currently incompatible with spring-vault-core v2.x.x. This is because of _spring-vault-core_'s dependency on _springframework_ v5.1.0.RELEASE (or higher).

I also tried to run using v2.1.0.RELEASE, and couldn't due to missing classes only found in spring framework v5 & up

**Comment by mp911de** [comment]
I think it should be possible to backport the fix to 1.1.x.

**Comment by mp911de** [comment]
The bugfix is now backported to Spring Vault 1.1.3. Care to give `1.1.3.BUILD-SNAPSHOT` a try to see whether the issue is fixed?

**Comment by kyleclark71** [comment]
Hi mp911de, I just tried the new version, and I'm no longer experiencing the issue. 

Thanks for the fix, my team appreciates it!

**Comment by mp911de** [comment]
Thanks for confirming the bug fix.
