### ISSUE TITLE
Let AwsIamAuthentication implement AuthenticationStepsFactory

### ISSUE THREAD

**Issue by jmirc** [spring-projects/spring-vault#338]
Spring Version: 2.0.6
Spring Cloud: Finchley.SR2

I am getting the following exception when the `spring.cloud.vault.authentication` property is set to `aws_iam`

```
Factory method 'reactiveVaultSessionManager' threw exception; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'vaultTokenSupplier' defined in 
org.springframework.cloud.vault.config.VaultReactiveBootstrapConfiguration: Bean instantiation via 
factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.springframework.vault.authentication.VaultTokenSupplier]: Factory method 
'vaultTokenSupplier' threw exception; nested exception is java.lang.IllegalStateException: Cannot 
construct VaultTokenSupplier from 
org.springframework.vault.authentication.AwsIamAuthentication@2f40a43. ClientAuthentication 
must implement AuthenticationStepsFactory or be TokenAuthentication
```

The `AwsIamAuthentication` doesn't extends  `AuthenticationStepsFactory` like the others authentication classes do.

For now, the only fix is to disable reactive vault

**Comment by mp911de** [comment]
Disabling Reactive Vault support in Spring Cloud Vault is the way to go if you don't require reactive Vault interaction.

`AwsIamAuthentication` bears the risk of blocking I/O via `AWSCredentialsProvider`. File or environmental credential-providers aren't the risky bit but providers that fetch credentials from remote services (e.g. `ContainerCredentialsProvider`, `InstanceProfileCredentialsProvider`).

We could move credential fetching into the bootstrap phase.

Out of curiosity: Which `AWSCredentialsProvider` are you using?

**Comment by jmirc** [comment]
We are using the `AwsCreadentialsProviderChain` which I think uses the `InstanceProfileCredentialsProvider` to get the aws role.
