### ISSUE TITLE
Add interceptors for Vault's namespace support

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#346]
Vault Enterprise allows multitenancy within a single Vault instance through namespaces. A namespace separates authentication backends and secret backends from other tenants. Since this is an entrerprise-only feature, we have to means to test our support properly.

The only thing that can provide are interceptors to set the `X-Vault-Namespace` header properly. This iterceptor must be registered by users in `RestTemplate` and `WebClient` accordingly (ideally by subclassing `VaultTemplate` and `ReactiveVaultTemplate` overriding `doCreateRestTemplate(…)` respectively `doCreateWebClient(…)` methods).

See also:
* #315
* #316
* spring-cloud/spring-cloud-vault#259

**Comment by CharlieReitzel** [comment]
I found the simplest way to support Vault Enterprise namespaces is as follows:

```
   static final String VAULT_NAMESPACE_DFLT = "foo/bar";

    @Value("${spring.cloud.vault.namespace:" + VAULT_NAMESPACE_DFLT + "}")
    String fooNamespace;

    @Bean
    public RestTemplateCustomizer forwardNamespaces() {
        log.info("forwardNamespaces - namespace: {}", fooNamespace);
        return (restTemplate) -> {
            log.info("customize - namespace: {}", fooNamespace);
            restTemplate.getInterceptors().add( VaultClients.createNamespaceInterceptor(fooNamespace) );
        };
    }
```
