### ISSUE TITLE
Read and Write API issues

### ISSUE THREAD

**Issue by vyask** [spring-projects/spring-vault#347]
VaultTemplate.write Issue:

MySecretData mySecretData = new MySecretData();
		mySecretData.setUsername("walter");
		mySecretData.setPassword("white");
vaultTemplate.write(
				"/secret/myapplication/user/3128",mySecretData);

Expected:
Sucesss

Actual:
404 - Not found error.

To make it work made following changes:

MySecretData mySecretData = new MySecretData();
		mySecretData.setUsername("walter");
		mySecretData.setPassword("white");
		HashMap<String,MySecretData> hm = new HashMap<String,MySecretData>();
		hm.put("data", mySecretData);
		
		try {
			vaultTemplate.write(
			"/secret/data/myapplication/user/3128",objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(hm));
		}catch(Exception e) {
		}

Note the change in path to include "data".
Vault API expects JSON object structured like {"data":{}}.
Converted target object to a Hashmap with a dummy key "data".
Used Jackson library to produce JSON and pass to write method.

VaultTemplate.read issue.

Vault API returns a JSON object with "data" and "metadata" sections.

**Comment by mp911de** [comment]
Use the [`VaultKeyValueOperations`](https://docs.spring.io/spring-vault/docs/current/api/org/springframework/vault/core/VaultKeyValueOperations.html) via `VaultOperations. opsForKeyValue("data", KeyValueBackend.versioned())`.

**Comment by vyask** [comment]
Hi Mark,Apologies but I tried in with VaultKeyValueoperations and continue to get '400 bad request' if I follow the examples as described.I may be missing something about Vault but I followed code samples as per documentation available online.thanksVyas

    On Friday, December 14, 2018, 4:48:54 PM EST, Mark Paluch <notifications@github.com> wrote:  
 
 
Closed #347.

**Comment by mp911de** [comment]
We've got a working sample in https://github.com/mp911de/spring-cloud-vault-config-samples at [`KeyValueTests`](https://github.com/mp911de/spring-cloud-vault-config-samples/blob/master/spring-vault/hello-world/src/test/java/example/helloworld/KeyValueTests.java#L50). This sample uses Vault 1.0 and [here's a pointer to how Vault is configured](https://github.com/mp911de/spring-cloud-vault-config-samples/blob/master/src/test/bash/setup_examples.sh#L18-L24).

You might want to [enable wire logging along using Apache's Http client](https://hc.apache.org/httpcomponents-client-ga/logging.html) to see what's happening on the wire.

**Comment by vyask** [comment]
Thanks Mark,
Got this to work finally. It wasn't an issue with the code since I coded exactly the same way but vault config on the back end.
I am running vault server on windows, instead of running the bash script, i executed few commands in that set up related to kv engine.
thanks much
Vyas
