### ISSUE TITLE
VaultResponse is incompatible with Vault 0.6.2 (missing warnings in VaultResponseSupport)

### ISSUE THREAD

**Issue by dtertman** [spring-projects/spring-vault#36]
The HTTP API for Vault now (as of 0.6.2) has a "warnings" field:
```
{
  "request_id":"f3fdbc6c-183e-1684-56dd-77b16eaac36d",
  "lease_id":"",
  "renewable":false,
  "lease_duration":2764800,
  "data":
  {
     "password":"test2",
     "username":"test"
  },
  "wrap_info":null,
  "warnings":null,
  "auth":null
}
```
This isn't bound in [VaultResponseSupport](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/support/VaultResponseSupport.java#L32) and while VaultResponseSupport [ignores unknowns](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/support/VaultResponseSupport.java#L31), VaultResponse [overrides that](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/support/VaultResponse.java#L31).  When Jackson tries to deserialize for `VaultOperations.read`, it fails.

```
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "warnings" (class org.springframework.vault.support.VaultResponse), not marked as ignorable (8 known properties: "lease_id", "wrap_info", "renewable", "auth", "lease_duration", "data", "request_id", "metadata"])
```

**Comment by mp911de** [comment]
Thanks, that's fixed with 4d337b1.
