### ISSUE TITLE
Improve Generic Type Handling in VaultTemplate

### ISSUE THREAD

**Issue by sappenin** [spring-projects/spring-vault#365]
Currently, neither [VaultOperations#read](https://docs.spring.io/spring-vault/docs/current/api/org/springframework/vault/core/VaultOperations.html#read-java.lang.String-java.lang.Class-) nor [VaultKeyValueOperations#get](https://docs.spring.io/spring-vault/docs/current/api/org/springframework/vault/core/VaultKeyValueOperations.html#get-java.lang.String-java.lang.Class-) support [ParameterizedTypeReference](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/ParameterizedTypeReference.html) when reading data from Vault. 

Given that RestTemplate _does_ support this extra/alternative parameter, is there any reason that `spring-vault` does not? As it stands now, something like this leads to a `ClassCastException`:

```
Map<String, MyCredential> credentialsMap = new HashMap<>();
credentialsMap.put("my-primary-credentials", new MyCredentials("shh"));

// Put the Map into Vault...
VaultKeyValueOperations keyValueNotVersioned = vaultTemplate.opsForKeyValue("secret", KeyValueBackend.KV_2);
keyValueNotVersioned.put("my-primary-credentials", credentialsMap);

// Triggers ClassCastException
Map<String, MyCredentials> result = keyValueNotVersioned.get("my-primary-credentials", Map.class).getData();
MyCredentials resultCreds = result.get("my-primary-credentials"); // ClassCastException: Returns a `java.util.LinkedHashMap` instead of a `MyCredentials`
```

To be fair, the ClassCastException above is correct -- in this case Jackson doesn't know how to deserialize the JSON coming from Vault because Jackson lacks any type information beyond `Map`, so it (i.e., Jackson) just defaults to using `LinkedHashMap`. When I try to type the `LinkedHashMap` as a `Map<String, MyCredentials` things _should_ blow up. 

That said, it would be nice if we could avoid this by allowing the API to accept a `ParameterizedTypeReference` so that Jackson can behave in a more expected manner when dealing with Collections. Thoughts here?

**Comment by cantara256** [comment]
So it sounds like there's no technical problem with adding parameterized types (e.g. read ParameterizedTypeReference), other than simplicity in the API?

We'd love to subclass VaultTemplate but unfortunately everything that's not public is private not protected, so it's impossible to subclass. We'll have to write a wrapper, which isn't too bad because the class is simple and we don't need all the functionality, but it would've been nice to be able to subclass to provide a simple `read(String key, ParameterizedTypeReference type)` method.

**Comment by mp911de** [comment]
> So it sounds like there's no technical problem with adding parameterized types

Adding a set of overloads seems a technical problem as it clutters the API.

> We'd love to subclass VaultTemplate but unfortunately everything that's not public is private not protected,

We should discuss APIs that you would like to see `protected`. How about continuing this discussion over a pull request? I suggest doing the exercise of introducing methods in a custom subclass. From there on you get the requirements what we should make `protected` in Spring Vault. Come back with a PR that applies the visibility changes to Spring Vault.

What do you think?

**Comment by cantara256** [comment]
Sounds good, I'll do that.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by xerZV** [comment]
@cantara256 any updates on that?
