### ISSUE TITLE
VaultClients do not take in consideration vaults with path

### ISSUE THREAD

**Issue by KrynaS** [spring-projects/spring-vault#413]
https://github.com/spring-projects/spring-vault/blob/22b916fba9dd98a0b7071640b67a51367b67967d/spring-vault-core/src/main/java/org/springframework/vault/client/VaultClients.java#L238

Hello, there is problem with this line, if I host my vaults like this:

https://myvault.com:8200/myvault1

It ends up as connection to https://myvault.com/myvault1/:8200/v1

**Comment by mp911de** [comment]
We're currently not considering `VaultEndpoint.path` in URL construction. Do you want to submit a pull request to fix the issue in `VaultClients.toBaseUri(…)`?

**Comment by KrynaS** [comment]
Ok I can do that.
