### ISSUE TITLE
Make LifecycleAwareSessionManager more extensible

### ISSUE THREAD

**Issue by radarsh** [spring-projects/spring-vault#415]
Sometimes it is necessary to extend all or part of the functionality of `LifecycleAwareSessionManager`. However, due to water-tight access restrictions on its members, one would end up duplicating most of `LifecycleAwareSessionManager` code in its subclass implementations rather than just overriding select methods. In order to make this class more [open-closed](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle) I recommend making the following changes:

- `LifecycleAwareSessionManager.TokenWrapper` be made protected / public
- Visibility of `token` field be increased to protected
- Provide public / protected accessors for `clientAuthentication` and `restOperations` fields.
- Make provision for scheduling using other types of triggers, such as `PeriodicTrigger` or `CronTrigger` and make `LifecycleAwareSessionManagerSupport.OneShotTrigger` protected / public.

**Comment by mp911de** [comment]
We can increase visibility of `TokenWrapper` and provide accessors for `token`. `clientAuthentication` and `restOperations` are constructor args and you should grab these if you're required to do so.
