### ISSUE TITLE
Support  key password and key alias

### ISSUE THREAD

**Issue by jiang-wei** [spring-projects/spring-vault#416]
Right it uses the keystore password to decrypt the keystore and the keys in the keystore.
And I cannot select which key in the keystore should use.

Nice to support key-password, key-alias just like application.properties in Spring

```
server.ssl.key-alias= # Alias that identifies the key in the key store.
server.ssl.key-password= # Password used to access the key in the key store.
```

**Comment by mp911de** [comment]
We should add a separate key password to decouple the key password from the keystore password.

How would we go about the key alias? How is that even configurable on a `SSLContext`?

**Comment by jiang-wei** [comment]
> We should add a separate key password to decouple the key password from the keystore password.
> 
> How would we go about the key alias? How is that even configurable on a `SSLContext`?

see: https://stackoverflow.com/questions/15201251/how-i-can-tell-alias-of-the-wanted-key-entry-to-sslsocket-before-connecting

use `chooseClientAlias`

```
    public String chooseClientAlias(String[] keyType, Principal[] issuers, Socket socket) {
        return "foo";
    }
```
