### ISSUE TITLE
Do not respect keystore type

### ISSUE THREAD

**Issue by jiang-wei** [spring-projects/spring-vault#417]
Hi,
I just read the code of 2.1.x

in SslConfiguration.java it read configs like key-store-type and trust-store-type but does not use them. Still use DEFAULT_KEYSTORE_TYPE,that is JKS

I cannot use a PKCS12 key store

**Comment by mp911de** [comment]
Why don't you use `new KeyStoreConfiguration(Resource resource, @Nullable char[] storePassword, String storeType)`?  `KeyStoreConfiguration`'s constructor is `public` and `ClientHttpRequestFactoryFactory` considers the store type when loading a `KeyStore` for (`KeyManagerFactory` and `TrustManagerFactory`).

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
