### ISSUE TITLE
@VaultPropertySource annotations in more than one @Configuration class

### ISSUE THREAD

**Issue by erikrz** [spring-projects/spring-vault#421]
I have an application that is separated by modules, each one having it's own Spring `@Configuration` class.I though that each one should have it's own `@VaultPropertySource` annotations, but, if I do the following:

```
@Configuration
@VaultPropertySource(value="kv/apidomain")
public class MyConfiguration {}
```

```
@Configuration
@VaultPropertySource(value="kv/anotherdomain")
public class AnotherConfiguration {
}
```
I get the following error: 

> The bean 'VaultPropertySourceRegistrar', defined in null, could not be registered. A bean with that name has already been defined in null and overriding is disabled.

Since Spring Boot 2.1,  Bean Overriding is disabled by default. Is there a way to avoid this without enabling Bean Overriding?
I found that if I put all my `@VaultPropertySource` annotations in one `@Configuration` class, I can get rid of this error, but I am not comfortable with that solution. Any ideas?

**Comment by mp911de** [comment]
Thanks for reporting the issue. The problem is on our side. We're registering `VaultPropertySourceRegistrar` multiple times without checking for presence. We need to check whether a bean with that name is already registered and if so, we can skip registration.

**Comment by lbornov2** [comment]
When will this fix be released?  This is a show-stopper for us.

**Comment by mp911de** [comment]
Scheduled 2.1.3 release for Monday, June 24.
