### ISSUE TITLE
LifecycleAwareSessionManager does not reconnect to Vault after server failures

### ISSUE THREAD

**Issue by mechero** [spring-projects/spring-vault#426]
## Set-up

* Spring Boot 2.1.2 application.
* Spring Cloud Vault starter: `spring-cloud-starter-vault-config`

Given this code to configure Vault Authentication

```java
@Configuration
public class VaultAuthentication extends AbstractVaultConfiguration {

    @Override
    public VaultEndpoint vaultEndpoint() {
        return VaultEndpoint.from("[some-vault-endpoint]");
    }

    @Override
    public ClientAuthentication clientAuthentication() {
        KubernetesAuthenticationOptions options = KubernetesAuthenticationOptions.builder()
                // not relevant
                .build();
        return new KubernetesAuthentication(options, restOperations());
    }

    @Bean
    @Override
    public SessionManager sessionManager() {
        ClientAuthentication clientAuthentication = clientAuthentication();
        Assert.notNull(clientAuthentication, "ClientAuthentication must not be null");
        int refreshTimeout = 30; // Overrides default
        LifecycleAwareSessionManagerSupport.FixedTimeoutRefreshTrigger refreshTrigger = new LifecycleAwareSessionManagerSupport.FixedTimeoutRefreshTrigger(
                refreshTimeout, TimeUnit.SECONDS);
        return new LifecycleAwareSessionManager(clientAuthentication, threadPoolTaskScheduler(), restOperations(), refreshTrigger);
    }
}
```

## Scenario

* The vault server goes down for a while, say 30 minutes.

## Outcome

* Token renewal process in `LifecycleAwareSessionManager` fails. `Cannot renew token` message is output and token is set to `Optional.empty()` [(see here)](https://github.com/spring-projects/spring-vault/blob/afdbdd67f1018634a536fa4e0f60a52d37b1860c/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L217).
* The `sessionManager` bean never tries again to renew the token. It doesn't invoke itself the `getSessionToken()` method so it doesn't initiate again the process to get a new, fresh token. Therefore, `sessionManager` remains in an invalid state indefinitely. 
* The vault server becomes available again and revokes all existing secrets.
* The service tries to connect to services using Vault (e.g. Cassandra) but the access is denied due to invalid permissions. 

## Expected Outcome

* `LifecycleAwareSessionManager` tries to re-login indefinitely, which makes it self-healing, and also as per [this message](https://github.com/spring-projects/spring-vault/blob/afdbdd67f1018634a536fa4e0f60a52d37b1860c/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L201).
* When Vault server comes back, the service performs a new login and it starts working again.

## A bit of analysis

I think this behavior might be caused by the combination of:

* [This line of code](https://github.com/spring-projects/spring-vault/blob/afdbdd67f1018634a536fa4e0f60a52d37b1860c/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L335)`token.ifPresent(tokenWrapper -> getTaskScheduler().schedule(task, createTrigger(tokenWrapper)));`. It does not include an `else` scenario to trigger a new login.

* Not having more interactions with the Vault server after the service has booted up and set up everything related to the Vault. Due to this, the VaultTemplate's interceptor ([this one](https://github.com/spring-projects/spring-vault/blob/c7b6557606b7e3a41a7982326612615c192adff1/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTemplate.java#L176)) does not restart the login process and the subsequent token renewal task. 

Let me know if I'm misunderstanding the whole flow and I should actually call somewhere `getSessionToken()` myself after detecting this situation. But, in that case, where do you recommend to implement this logic?

Thanks,
Moises

**Comment by mp911de** [comment]
Thanks for your detailed report. I currently fail to understand where the blind hole is.

The purpose of `LifecycleAwareSessionManager` is to make sure that a component, that wants to interact with Vault obtains a valid session token and to not perform a login for each `getSessionToken()` but buffer these requests. 

The active component in `LifecycleAwareSessionManager` is to keep a token alive.

I struggle currently with understanding:

> * The vault server becomes available again and revokes all existing secrets.
> * The service tries to connect to services using Vault (e.g. Cassandra) but the access is denied due to invalid permissions.

When Vault comes back up, it is natural to revoke secrets because we weren't able to renew these. Please help me understand how Spring Vault could prevent this. I currently do not see anything that we could do here.

> access is denied due to invalid permissions

Is this the consequence of the expired session token?

Please note, that when your Vault server is down, that `SecretLeaseContainer` is also no longer able to renew leases. Any I/O failures during renewal stop Lease renewal.

Lease renewal happens, in general, a couple of seconds before the lease expires. If Vault goes down then the expiry time is exceeded and Vault again revokes leases by the time it is back up again.

**Comment by mechero** [comment]
Thanks for the quick response.

To keep it simple: how can I know from within the application that the lease renewal failed and something went wrong so I can (try to) re-login to the Vault? Should I use a listener with `SecretLeaseContainer`?

Right now, `LifecycleAwareSessionManager` doesn't notify directly in any way that it couldn't renew the lease. The Vault just does its part indeed: revokes secrets and, as a consequence, access is denied. The problem is that, from the application side, this should be known as soon as possible to react to that and perform any needed operation.

**Comment by mp911de** [comment]
You can register your own listener via `SecretLeaseContainer.addErrorListener(…)`

>  so I can (try to) re-login to the Vault

What is the point of performing a re-login? You will get a new session token. 
`SecretLeaseContainer` does the same already when attempting to renew a lease.

**Comment by mechero** [comment]
> You can register your own listener via SecretLeaseContainer.addErrorListener(…)

I see now. What happened is that, for some reason, I missed that part of the docs and I implemented the code that read secrets in a different way:

```java
final VaultAuthentication auth;
// ...
auth.vaultTemplate().read(secretsPath, MySecretsClass.class);
```

And, in this case, I fully depend on `LifecycleAwareSessionManager`'s scheduled task for token renewal. Funny thing is that it works perfectly as long as you don't rotate secrets and connection works fine. 

So now I know how I could make it work, thanks for that. And I think I understood why `LifecycleAwareSessionManager` does a "best-effort" token renewal and stops renewing it without having support for listeners: `VaultTemplate` is intended to be used for one-shot Vault operations, not for retrieving secrets and keeping the lease. Just correct me if I'm wrong.

**Comment by mp911de** [comment]
Thanks for your response.

On a related note: You could integrate with [Spring Retry](https://github.com/spring-projects/spring-retry) to catch network hiccups that might occur at times by overriding `VaultTemplate.doWithSession(…)` but that is entirely application-specific regarding their needs.

**Comment by mechero** [comment]
One extra question, since I'm still experiencing issues related to this and I think I'm still missing something in terms of how to use Spring Vault in my specific use case.

To add some extra context, I'm using Periodic Tokens in Vault: https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens

This means, according to the docs:

> Therefore, as long as a system is actively renewing this token -- in other words, as long as the system is alive -- the system is allowed to keep using the token **and any associated leases**.

My Cassandra secrets, no matter if I use now the `SecretLeaseContainer`, are an **associated lease** for Vault since I got them using the Authentication token. This means the secrets will be revoked if I fail to renew the lease for the periodic Vault authentication token. As additional info, I'm using a relatively long TTL for the Cassandra secrets (longer than the TTL for the Authentication token).

Therefore, what happens now is that when `LifecycleAwareSessionManager` fails to renew the Vault token lease for whatever reason (for instance, Vault is unreachable for 10 minutes), secrets are revoked **and the application doesn't have a way to detect this**. 

So, what I'm actually missing is a listener approach for `LifecycleAwareSessionManager` similar to the one in`SecretLeaseContainer`, because the app needs to know that the token could not be renewed and act upon that even before the next secret lease renewal attempt happens (which is expected to fail anyway). 

Do you recommend a different way to detect this? I couldn't find it in docs.

**Comment by mp911de** [comment]
There are currently no listeners/events available in `LifecycleAwareSessionManager`. Can you file a separate ticket to add events to the session manager? We had a PR once but that didn't really go in the right direction.

Let's revisit how renewal works. For both, login tokens and leases, we run renewal just before the token expires. With this strategy, if renewal fails (Vault server is down), it's almost guaranteed that when Vault comes up again, tokens will expire.

If we would switch renewal to a much earlier time (e.g. renewal after 50% of the TTL is reached), we would add a security buffer. If renewal fails, this isn't a problem expecting that Vault will come back up before reaching 100% of the TTL to expire. We would need to make sure to re-attempt token/lease renewal.

**Comment by mp911de** [comment]
I reopened the ticket since during the discussion the actual goal of this one changed

**Comment by mechero** [comment]
Thanks! I created https://github.com/spring-projects/spring-vault/issues/431.

**Comment by mp911de** [comment]
Authentication events are now in place. The only missing bit to address this issue is controlling over whether the `LoginToken` should be removed on renewal failure. Currently, all renewal failures cause the token to be reset. We could introduce a control flag whether the token should be retained after a renewal failure and expose the `renew()` method. This way, an application could listen for renewal failures (`LoginTokenRenewalFailedEvent`) and call the `renew()` method after a certain time.

With sufficient TTL, the token should be kept alive and we're closing that loophole.

What do you think?

**Comment by mechero** [comment]
Great, thanks! I'll give it a try and provide some feedback.

**Comment by mp911de** [comment]
We've introduced now means to configure `Lease` retention on renewal failures. Leases are dropped by default but now you can configure the session managers and `SecretLeaseContainer` to retain these for manual retries.

**Comment by Achalveer** [comment]
Could you please let me know how this issue got resolved ? 
relogin to vault if vault server goes down for some time and spring cloud is not able to renew lease.
