### ISSUE TITLE
No ops for deleting metadata in Vault template

### ISSUE THREAD

**Issue by zak905** [spring-projects/spring-vault#432]
It would be nice to have operations for deleting and getting metadata implemented for `kv` (and same thing for secrets I suppose), like the ones specified by vault CLI:
```
vault kv metadata
Usage: vault kv metadata <subcommand> [options] [args]

  This command has subcommands for interacting with the metadata endpoint in
  Vault's key-value store. Here are some simple examples, and more detailed
  examples are available in the subcommands or the documentation.

  Create or update a metadata entry for a key: 

      $ vault kv metadata put -max-versions=5 secret/foo

  Get the metadata for a key, this provides information about each existing
  version:

      $ vault kv metadata get secret/foo

  Delete a key and all existing versions:

      $ vault kv metadata delete secret/foo

  Please see the individual subcommand help for detailed usage information.

Subcommands:
    delete    Deletes all versions and metadata for a key in the KV store
    get       Retrieves key metadata from the KV store
    put       Sets or updates key settings in the KV store
```

The reason why metadata operations are important is because attempting to delete a key will only delete the data it contains, and the key will still be there. So to delete a key completely, the metadata needs to be deleted. As a workaround right now, I will be using rest API call directly, anyways, if this is of interest, I could submit a PR eventually, it could take some time however.

**Comment by mp911de** [comment]
Thanks for the ticket. That's a good enhancement. Pull requests are welcome. We should probably introduce a dedicated interface (`VaultKeyValueMetadataOperations`) that can be obtained from `VaultVersionedKeyValueOperations` to keep `VaultVersionedKeyValueOperations` focussed on key operations.
