### ISSUE TITLE
VaultMount does not allow for options to be specified

### ISSUE THREAD

**Issue by maciejqantas** [spring-projects/spring-vault#433]
Affected version: 2.1.2

To properly create a KV v2 versioned secret backend, options must be specified as per https://www.vaultproject.io/api/system/mounts.html#options.
Also, the link above incorrectly shows that `options` should be a field of `config`. It is a separate field, as per https://github.com/hashicorp/vault/blob/master/api/sys_mounts.go#L137. A fix has been requested in https://github.com/hashicorp/vault/issues/4601#issuecomment-500802035.

Currently, `VaultMount` does not allow for a specification of `options`, only `config` is exposed. This way, if a mount of `type` set to `kv` is created, it's not versioned and versioning must be enabled separately.

A workaround is to use `VaultTemplate` directly (as opposed to `VaultSysOperations`) and execute `write("sys/mounts/mymount", "{\"type\": \"kv\", \"options\": {\"version\": \"2\"}}")`.

**Comment by mp911de** [comment]
That's a good enhancement proposal. Do you want to submit a pull request?

**Comment by maciejqantas** [comment]
Sure, I'll give it a go soon.

**Comment by maciejqantas** [comment]
@mp911de I will need your help here.
Tests are failing for older Vault versions. Is there a mechanism to run tests for specific vault versions only?

**Comment by mp911de** [comment]
You already answered your first question. No need for a separate test class. If there's no version check yet, then add it like it is done in https://github.com/spring-projects/spring-vault/blob/c7b6557606b7e3a41a7982326612615c192adff1/spring-vault-core/src/test/java/org/springframework/vault/core/VaultSysTemplateIntegrationTests.java#L55-L62.

**Comment by maciejqantas** [comment]
@mp911de thanks for that! I didn't even realise it was in the same class I worked on 😊 

Travis seems happy, have a read of the code please.
