### ISSUE TITLE
Add SpEL support for @Secret annotation

### ISSUE THREAD

**Issue by Tomschi** [spring-projects/spring-vault#436]
I want to externalize the keystore and backend property of @Secret annotation.

`@Secret(value = "${vault.keyspace}")`

But the following exception is thrown:
`org.springframework.data.keyvalue.core.UncategorizedKeyValueException: Not enough variable values available to expand 'vault.keyspace'; nested exception is java.lang.IllegalArgumentException: Not enough variable values available to expand 'vault.keyspace'`

Is it possible to add SpEL support?

**Comment by mp911de** [comment]
That should be possible. Ideally, we handle this aspect in Spring Data KeyValue. I filed [DATAKV-268](https://jira.spring.io/browse/DATAKV-268).
