### ISSUE TITLE
Allow re-reading Kubernetes service token for each authentication

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#449]
The discussion at https://github.com/spring-cloud/spring-cloud-vault/issues/339 explains a use-case where short-lived TTLs are used in combination with Kubernetes. Kubernetes Service Account JWTs have a short-lived TTL. Caching these tokens (read: not re-reading the token file) causes subsequent login attempts to fail (assuming the login attempt happens after the JWT token has expired).

We should:

* Change `KubernetesServiceAccountTokenFile` that it re-reads the JWT token on each request
* Introduce a cached `KubernetesJwtSupplier` to retain current functionality and configure the `KubernetesAuthenticationOptions` accordingly
* Update our docs

**Comment by jeroenjacobs79** [comment]
Was this fixed? Or is there a reason it won't be fixed?

**Comment by mp911de** [comment]
This is fixed in 28976b1 for Spring Vault.
