### ISSUE TITLE
Update docs reflecting Apache HttpClient's wire logging

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#451]

**Comment by ajeydudhe** [comment]
NOTE: Apache HttpClient's https://hc.apache.org/httpcomponents-client-4.5.x/logging.html[wire logging] can be enabled through logging configuration. Make sure to not accidentally enable logging as logs may expose traffic between your application and Vault in plain text.

Can we explicitly mention at the end that: 
Make sure to not accidentally enable logging as logs may expose traffic between your application and Vault in plain text **_resulting in the vault secrets getting leaked._**

**Comment by mp911de** [comment]
Thanks a lot. We have improved our wording.
