### ISSUE TITLE
Add support to override  endpointUri for awsIamAuthentication

### ISSUE THREAD

**Issue by vic0de** [spring-projects/spring-vault#457]
At the moment its not possible to override endpointUri via vault properties for awsIamAuthentication. 

Method is there to be able to set endpointUri but this one is never invoked:
https://github.com/spring-projects/spring-vault/blob/c7b6557606b7e3a41a7982326612615c192adff1/spring-vault-core/src/main/java/org/springframework/vault/authentication/AwsIamAuthenticationOptions.java#L263-L269

We have a requirement to change this url to https://sts.*aws-region*.amazonaws.com because provided iam role is bound to specific aws region.

**Comment by mp911de** [comment]
Care to elaborate on 

> not possible to override endpointUri via vault properties for awsIamAuthentication.


There are no `VaultProperties` in Spring Vault. Do you mean Spring Cloud Vault?

**Comment by vic0de** [comment]
Yes, I mean Spring Cloud Vault.

**Comment by mp911de** [comment]
Can you please file a ticket at https://github.com/spring-cloud/spring-cloud-vault/issues as we cannot migrate tickets across organizations?

**Comment by vic0de** [comment]
Sure will do. thank you!
