### ISSUE TITLE
GoogleApacheHttpTransport fails with newer Apache HttpClient versions

### ISSUE THREAD

**Issue by jesseeichar** [spring-projects/spring-vault#463]
A little background.  I am using `spring-cloud-starter-vault-config` with bootstrap.yml config:

```
spring:
  cloud:
    vault:
      authentication: GCP_IAM
      gcp-iam:
        role: read-config
        gcp-path: gcp
```

When using this configuration I get a `java.lang.UnsupportedOperationException` (Stack trace at bottom of issue).  After doing research into the issue I have learned that it is caused by `com.google.api.client.googleapis.apache.GoogleApacheHttpTransport` which calls `com.google.api.client.http.apache.ApacheHttpTransport` which is deprecated.  I think it worked for older Apache httpcomponents version but the more recent versions that I have been using is does not.   

The constructor: `GcpIamAuthentication(GcpIamAuthenticationOptions,RestOperations)` calls `GoogleApacheHttpTransport.newTrustedTransport()` which calls `com.google.api.client.http.apache.ApacheHttpTransport` which is deprecated (and doesn't work with recent httpcomponents versions)

To work around this issue we can't directly use `GoogleApacheHttpTransport.newTrustedTransport()` until they fix the implementation.  Instead we will have to use a different implementation.  The class `GoogleApacheHttpTransport` is fine.  The fix would to be to change a single line:

   `import com.google.api.client.http.apache.ApacheHttpTransport;`
the v2 version should be used.
   `import com.google.api.client.http.apache.v2.ApacheHttpTransport;`

We will also need to add a dependency on: `com.google.http-client:google-http-client-apache-v2`

**Comment by mp911de** [comment]
Thanks for report. How about switching to `NetHttpTransport`? We could fix the issue that way without adding another dependency and we could fix it in the maintained branches as it does not require a change to our dependency setup.
