### ISSUE TITLE
Request sent in XML instead of JSON when com.fasterxml.jackson.dataformat.xml.XmlMapper exists in the classpath

### ISSUE THREAD

**Issue by ykoasanto** [spring-projects/spring-vault#47]
We are running into issue with request sent in XML format instead of JSON, when com.fasterxml.jackson.dataformat.xml.XmlMapper exists in the classpath. This can be fixed by specifying the content-type to application/json, but it's very cumbersome to do this each time we want to make Vault request.

Also in certain places such as ClientCertificateAuthentication the content-type is set to null, resulting in the MappingJackson2XmlHttpMessageConverter being used and XML being sent

**Comment by mp911de** [comment]
That's fixed now with `1.0.0.BUILD-SNAPSHOT` available from https://repo.spring.io/snapshot/.
