### ISSUE TITLE
AbstractVaultConfiguration#secretLeaseContainer() is misleading

### ISSUE THREAD

**Issue by IrinaTerlizhenko** [spring-projects/spring-vault#486]
I looks like the `@return` section of the `AbstractVaultConfiguration#secretLeaseContainer()` javadoc contains the line from `AbstractVaultConfiguration#sessionManager()`.
```
/**
* @return the {@link SessionManager} for Vault session management.
*/
public SecretLeaseContainer secretLeaseContainer() {
```
Link: https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/config/AbstractVaultConfiguration.java#L139

Could the returned value in the javadoc be updated please?

**Comment by mp911de** [comment]
Good catch, we need to fix that.
