### ISSUE TITLE
Reshape APIs

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-vault#49]
Currently the APIs of VaultTemplate and VaultClient look a lot like RestTemplate. If users want to do the REST operations, they already have RestTemplate to do this. It would be nice if the VaultClient APIs reflected the intent rather than the underlying REST semantics.

**Comment by mp911de** [comment]
This change should reshape `VaultSession` as well, `VaultSession` continues the approach from `VaultClient`.

**Comment by mp911de** [comment]
There are two issues in this ticket:
1. After discussing with @rwinch we found out that Rob wasn't aware of `VaultOperations`. 
2. Spring Vault defines a `RestTemplate`-like through `VaultClient`. It has a huge API surface and is somewhat an abstraction over `RestTemplate` with little benefit.

I created two PR's to evaluate different approaches (functional `VaultClient` exposing less API surface, removal of `VaultClient`).
