### ISSUE TITLE
write call is returning Mono.empty() when request failed with 404 Not Found

### ISSUE THREAD

**Issue by philaw** [spring-projects/spring-vault#503]
Our app tried to write to vault and vault returned 404 because the path doesn't exist.

**Expected behaviour**: We assumed in such scenario spring-vault would result mono error

**Actual behaviour**: it actually returns Mono.empty().

Have a look at this method in vault/core/ReactiveVaultTemplate.java

```
	private static <T> Mono<? extends T> mapOtherwise(ClientResponse response, String path) {

		if (response.statusCode() == HttpStatus.NOT_FOUND) {
			return Mono.empty();
		}

```

NOTE: the problem is when vault returns 204 No Content, spring-vault also results in Mono.empty(), which makes it almost impossible for downstream to handle 204 and 404 responses.

**Comment by mp911de** [comment]
Good catch. That is a bug that we should fix in `write` and `delete`. `Mono.empty()` should apply only to 404's received through `read()`. 404's in `write` and `delete` should propagate an error.

**Comment by philaw** [comment]
Thanks @mp911de 

Can I also ask when 2.1.5 will be out?

**Comment by mp911de** [comment]
Releases are mostly driven by the content. We released 2.1.4 and 2.2.0 recently so it may take to January until we ship another release.

**Comment by raoofm** [comment]
@mp911de how do we want to fix this, i can do the pr just want to see if you have figured it out or it need investigation.

**Comment by mp911de** [comment]
We need to refine `ReactiveVaultTemplate.mapResponse(…)` and `mapOtherwise(…)`. Currently, `mapResponse(…)` considers `HttpStatus.NOT_FOUND` to be a non-error outcome. We need to retain that functionality for the `read(…)` and `doRead(…)` cases but not for `write` and `delete`.

Happy to review a pull request and help you with the next steps.
