### ISSUE TITLE
Fix EnvironmentVaultConfiguration documentation

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#510]
The documentation for `EnvironmentVaultConfiguration` lists wrong properties. Also, the reference documentation does not list all the properties of `EnvironmentVaultConfiguration`.

**Comment by raoofm** [comment]
@mp911de I can't find this change in the latest snapshot. Also #503

**Comment by mp911de** [comment]
This change was built and deployed with https://build.spring.io/browse/SPRINGVAULT-VAULT-339/log and https://build.spring.io/browse/SPRINGVAULT-VAULT13-6/log for `2.3.0.BUILD-SNAPSHOT` (spring-vault-core-2.3.0.BUILD-20191202.091840-7.jar) respective `2.2.1.BUILD-SNAPSHOT` (spring-vault-core-2.2.1.BUILD-20191202.091839-5.jar) versions.
