### ISSUE TITLE
Allow SSL configuration using PEM certificates

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-vault#514]
Spring Vault allows custom trust material to be configured for HTTPS connections to Vault by [providing Java Keystore (.jks) files](https://docs.spring.io/spring-vault/docs/current/reference/html/#vault.client-ssl). This requires that users convert certificates from standard formats like PEM to the Java-specific JKS format. 

It would be nice if custom trust material could be provided to Spring Vault in the PEM format that is more common and easier for users to acquire. 

Spring CredHub does this by allowing one or more `caCertFiles` to be provided in the [client connection options](https://github.com/spring-projects/spring-credhub/blob/master/spring-credhub-core/src/main/java/org/springframework/credhub/support/ClientOptions.java#L44-L57) and using any provided certificate files when [configuring the HTTP connections](https://github.com/spring-projects/spring-credhub/blob/master/spring-credhub-core/src/main/java/org/springframework/credhub/configuration/ClientHttpRequestFactoryFactory.java#L147). It is likely the [relevant support code](https://github.com/spring-projects/spring-credhub/blob/master/spring-credhub-core/src/main/java/org/springframework/credhub/configuration/SslCertificateUtils.java) could be re-used by Spring Vault.

**Comment by radarsh** [comment]
Changing the default values of `vault.ssl.trust-store-type` and `vault.ssl.key-store-type` if one is not provided to `PEM` has caused a breaking change for us.

We were previously using Spring Vault 2.2.3 but didn't have the `store-type` configured. Upgrading to Spring Vault 2.3.x means it now suddenly expects PEM format stores and our existing JKS stores are not loaded.

There is no mention of the `store-type` properties in the [Spring Vault reference documentation](https://docs.spring.io/spring-vault/docs/current/reference/html/#vault.core.environment-vault-configuration) / release notes / migration guide.
