### ISSUE TITLE
Support for Vault Agent

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-vault#515]
With the introduction of [Vault Agent](https://www.vaultproject.io/docs/agent/index.html) that can be deployed as a side-car, the use of Vault Token by the client is now optional.  The Spring Vault library does not allow having an empty Vault token, thus making it impossible to be used with Vault Agent.

https://github.com/hashicorp/vault/issues/7987

**Comment by aantono** [comment]
It seems like adding an empty/null check for https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTemplate.java#L197 would be a good start

**Comment by mp911de** [comment]
Using Vault Agent requires that we don't use a `SessionManager` at all to avoid authentication in the first place. We need to introduce new constructors for `VaultTemplate` and `ReactiveVaultTemplate` to construct both instances with a single `RestTemplate` that does not require the token at all.

**Comment by aantono** [comment]
I'm afraid the solution might be a bit too simplistic, as the change effectively just created a constructor that takes a custom `RestTemplateBuilder`, so that would require a fully manual creation of the template, without ability to take advantage of `VaultClients` helper methods which pre-configure the rest template with all the needed settings for accessing Vault.

Can this be simplified by simply calling `doCreateRestTemplate` for both - `statelessTemplate` and `sessionTemplate` inside the constructor, without forcing the user to define everything manually?

**Comment by aantono** [comment]
It would be nice to enable automatic configuration of using Vault Agent via properties by adding another `AuthenticationMethod` kind -> `VaultAgent`, so that one does not require to manually override the `VaultTemplate` in those cases.

**Comment by mp911de** [comment]
While I understand the desire of a simple approach, we need to consider that we have a certain architecture to respect which is the arrangement of `ClientAuthentication` and `SessionManager` beans. Our `AbstractVaultConfiguration` has no means to express conditional bean registration. 

Conditional bean registration is a Spring Boot concern. Returning a special kind of token would spread the implementation detail of using a Vault Agent across multiple components. Right now, this feature is encapsulated by `VaultTemplate`. Configuring `VaultTemplate` when only using Spring Vault code is a matter of overriding `AbstractVaultConfiguration.vaultTemplate()`. We have no good way to slice our configuration any further without putting each component in its own configuration class.

We can for sure introduce a certain degree of convenience with Spring Cloud Vault as Spring Cloud is based on Spring Boot and we can conditionally omit bean configuration when using Vault Agent's auth caching.

**Comment by aantono** [comment]
That would be awesome, if we can make this magic take place in Spring Cloud Vault library!
Thanks!!!
