### ISSUE TITLE
Authentication {mount} paths are URL-encoded

### ISSUE THREAD

**Issue by alehlapatsin** [spring-projects/spring-vault#532]
The following template is being used in KubernetesAuthentication.java: `auth/{mount}/login`
The problem if `kubernetes-path` is set to `hello/world`, the result path will be `auth/hello%2Fworld/login`, which is not correct.

**Comment by mp911de** [comment]
Thanks for raising this issue. We face the same issue in other authentication methods. Care to address these in your pull request #533 as well? The more relevant changes we can collect into a release the earlier we can ship a bugfix release.

**Comment by alehlapatsin** [comment]
@mp911de I updated the PR with the other fixes. Could you please take a look?
