### ISSUE TITLE
Is it possible to define two VaultTemplate in the same application?

### ISSUE THREAD

**Issue by thboileau** [spring-projects/spring-vault#548]
Hello,

we wonder if there could be an issue in the way SpringVault configures vaultTemplate.

In the same Spring-boot based application, we would like to have two distinct VaultTemplate instances that target distinct Vault servers with distinct role/secret identifiers.

**What we expect.**
Before issuing its first request to Vault, the SessionManager logs in to Vault.
So we should see:
 - request to log in into Vault
 - first request to Vault
 - second request to Vault
 - etc

This sequences of calls should be repeated for every Vault server instance.

**What we notice.**
There is only one login call (nb: to server1).
Which means that the other VaultTemplate has never logs in, so every subsequent calls fails miserably with a 403 response.

**What we suspect.**
The AbstractVaultConfiguration is more or less reused. It's perhaps due to the conjunction of "@Configuration", "@Bean" inside the AbstractVaultConfiguration class.

What do you think about this issue?

Our configuration code for server1 (which is duplicated/adapted for server2): 
```java
@Configuration
public class VaultServer1Config extends AbstractVaultConfiguration {

    @Value("${vault.server1.url}")
    private String vaultUrl;

    @Value("${vault.server1.provisioning.role-id}")
    private String vaultProvisioningRoleId;

    @Value("${vault.server1.provisioning.secret-id}")
    private String vaultProvisioningSecretId;

    @Override
    @Bean(name = "vaultTemplateServer1")
    public VaultTemplate vaultTemplate() {
        return super.vaultTemplate();
    }

    @Override
    public VaultEndpoint vaultEndpoint() {
        try {
            return VaultEndpoint.from(new URI(vaultUrl));
        } catch (URISyntaxException e) {
            throw new IllegalArgumentException(e.getMessage(), e);
        }
    }

    @Override
    public ClientAuthentication clientAuthentication() {
        AppRoleAuthenticationOptions options = AppRoleAuthenticationOptions
                .builder()
                .path("approle")
                .roleId(AppRoleAuthenticationOptions.RoleId.provided(vaultProvisioningRoleId))
                .secretId(AppRoleAuthenticationOptions.SecretId.provided(vaultProvisioningSecretId))
                .build();

        return new AppRoleAuthentication(options, restOperations());
    }
}
```

**Comment by mp911de** [comment]
Spring's `Abstract…Configuration` classes support the typical use-case in which a single endpoint is used with a single configuration object graph (client, session manager, template).

You can configure as many beans as you like but then you can no longer benefit from the `AbstractVaultConfiguration` infrastructure. Adding multiple beans interferes with bean resolution unless primary beans are declared as `@Primary`. That being said, you need to declare and wire the `SessionManager` and `VaultTemplate` beans in your own configuration.

**Comment by thboileau** [comment]
thanks for clarifying that `AbstractVaultConfiguration` supports the typical use-case and not all possible use cases. This is not quite clear in documentation.
