### ISSUE TITLE
Incorrect assert message in VaultTransitTemplate:decrypt

### ISSUE THREAD

**Issue by MLSTRM** [spring-projects/spring-vault#550]
https://github.com/spring-projects/spring-vault/blob/c41403a68981931014dfd03aaccfc4923521187f/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTransitTemplate.java#L267
The assert at the start of decrypt(String keyname, Ciphertext ciphertext) asserts on the content of the keyName, but the message reports that the Ciphertext is invalid

**Comment by mp911de** [comment]
Good catch. Do you want to submit a pull request for the fix?

**Comment by MLSTRM** [comment]
I've created a PR here - https://github.com/spring-projects/spring-vault/pull/551
