### ISSUE TITLE
ClientCertificateAuthentication path cannot be configured

### ISSUE THREAD

**Issue by pmv** [spring-projects/spring-vault#557]
I'm a little surprised this is a documented property if it's not used, but as far as I can tell it's not supported.  I believe adding support will require changes to both spring-vault and spring-cloud-vault-config, so the issue could have been reported in either project.

In spring-vault, it looks like the path is hardcoded as 'cert': https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/authentication/ClientCertificateAuthentication.java#L81-L82

Once it is configurable, it looks like spring-cloud-vault will have to pass in the existing property here: https://github.com/spring-cloud/spring-cloud-vault/blob/4118d4a076167c145cea4fcdfdd81cf3cc2b4490/spring-cloud-vault-config/src/main/java/org/springframework/cloud/vault/config/ClientAuthenticationFactory.java#L124-L125

Lack of support may make us reconsider the approach we were going to take with vault (potentially change plans and use 'cert' to avoid waiting for a release), but if we decide to move forward, I may submit a PR next week.

**Comment by mp911de** [comment]
Thanks for bringing this issue up. We should introduce a configuration object to make the authentication backend path configurable.

**Comment by pmv** [comment]
Thank you!
