### ISSUE TITLE
Support for LDAP authentication 

### ISSUE THREAD

**Issue by kuldikin** [spring-projects/spring-vault#566]
Hello, does it make sense to support LDAP authentication? If so, i can do it.

**Comment by mp911de** [comment]
Typically, applications use authentication schemes that qualify for machine authentication. LDAP/username-based schemes are human schemes and therefore we don’t support these. Each time there’s a username/password combination used for machine authentication it indicates a improper authentication scheme.

**Comment by kuldikin** [comment]
Thanks for the answer.  At my company, the admins did not want to support two authentication methods, and we were forced to make an ldap implementation.  I agree that this is not the right approach and it is not worth promoting it to the masses.  Ok, I'm closing the ticket.
