### ISSUE TITLE
Remove all newlines in PKCS7 from EC2MetaData

### ISSUE THREAD

**Issue by fz-29** [spring-projects/spring-vault#571]
The AWS EC2 authentication relies on EC2 Meta Data response which provides PKCS7. It has several newlines and to get ride of it the code has the line https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/authentication/AwsEc2Authentication.java#L192

Shouldn't it be changed from
```login.put("pkcs7", pkcs7.replaceAll("\\r", "").replace("\\n", "")); ```
to
```login.put("pkcs7", pkcs7.replaceAll("\\r", "").replaceAll("\\n", "")); ```
?

**Comment by mp911de** [comment]
Good catch. Care to submit a pull request. Out of curiosity, how did you spot the bug?

**Comment by fz-29** [comment]
@mp911de I will raise a PR.
I was actually doing a local development for EC2 login and was serving a mocked PKCS7 from local server. Then during some debugging process I spotted this.
