### ISSUE TITLE
Improve Spring Vault reference documentation to cover kv v1 and v2 usage

### ISSUE THREAD

**Issue by adamlehenbauer** [spring-projects/spring-vault#574]
I followed some of the examples in the reference documentation for reading and writing values to a simple kv store (which happened to be V2) but these don't work with that version

```
vaultTemplate.write("secret/myapp", secrets);
VaultResponseSupport<Secrets> response = vaultTemplate.read("secret/myapp", Secrets.class);
```

[This stackoverflow answer](https://stackoverflow.com/a/52605300/886217) led me to the solution, which is to use the `VaultKeyValueOperations`, that's not mentioned in the reference docs at all. There are ways to get the vaultTemplate.read()/write() approach working, but it involves confusing extra layers of wrapper objects to deserialize the data element at the root of the response, and an extra `/data/` path element in the request.

I'm probably not the only one to to choose a V2 kv store (why wouldn't you choose the latest if you're not constrained?) and struggle with the available online documentation. At the least, a callout note that v2 kv stores need to use `VaultKeyValueOperations` would save everyone else on this path time troubleshooting and searching.

**Comment by mp911de** [comment]
Sorry for inconvenience. The documentation is based on key-value version one and we never managed to overhaul the docs to suggest the Key-Value-specific API. Feel free to submit a pull request so we can improve the reference documentation.
