### ISSUE TITLE
ReactiveVaultTemplate for the key-value backend version 2

### ISSUE THREAD

**Issue by amrynsky** [spring-projects/spring-vault#576]
It would be great if `ReactiveVaultTemplate` supports KV backend v2 similar to non-reactive version. 

As a workaround, it's possible to use the current client and just add `data` to the path and wrap all POJO into `data` element but having built-in support would simplify v1->v2 migration.

**Comment by mp911de** [comment]
Feel free to submit a pull request. We initially didn't provide any higher-level API as we waited for signals how/whether the reactive API will be used.

**Comment by tweiand** [comment]
Working on a PR for the reactive versioned/unversioned key-value operations (I can potentially work on the other operations classes after I am done with this). Seems pretty straight forward.

I am starting to collect some questions. Is this enhancement the right place to ask questions until I get a PR created?

**Comment by mp911de** [comment]
Great news, @tweiand. This is the right place to discuss design and questions.

**Comment by tweiand** [comment]
Started putting code in the `enhancement-576` branch of my fork. Unit tests are created and working for V1. Have not been able to look into this for a few weeks, but, hopefully will have more time now.

Here is my current plan:
- Port the imperative code to be reactive
- Fix my current initialization of `ObjectiveMapper` in `ReactiveVaultKeyValueAccessor`
- Cleanup of code & work on JavaDocs and attribution

**Comment by tweiand** [comment]
**_Update on this:_** I have integration tests for the new code and they are all passing. All JSON parsing done with `WebClient`, no extra `ObjectMapper` needed. I am not ready for a review yet, but, I am good with people starting to look at the code with the assumption that things will be changing.

Left to do before requesting review:
- Ensure code coverage & static analysis (both unit and integration tests)
- Reduce/Remove duplicate code
- Finish reviewing changes for new APIs
- Update all JavaDocs
- Rebase for Spring Javaformat

General comments so far about the repo:
- Thank you for making new tests easy!
- Some fun gems in here for dynamically creating generic `Type`s

**Comment by tweiand** [comment]
I plan on having a MR ready for review at the end of the week.

**Comment by tweiand** [comment]
Finding time to complete this. Had other priorities pop up😀

**Comment by tweiand** [comment]
Still working on this, but, away from my laptop for two weeks.

**Comment by tweiand** [comment]
May I please get initial feedback on #807? It still needs work on the java docs and maybe some code deduplication. Wanted to get the conversation started.

**Comment by tweiand** [comment]
Hey all! Can I please get an initial review of #807 please? Once I have the initial feedback I can finish this up.

**Comment by mp911de** [comment]
I've been on vacation for the past weeks and I'll have a look in the next days.
