### ISSUE TITLE
Support for KV Patch in VaultTemplate

### ISSUE THREAD

**Issue by yfaney** [spring-projects/spring-vault#585]
Hi, our team needs a KV Patch operation in Spring Boot and I was wondering if we can get a feature of KV Patch operation in VaultTemplate or not.

Here is the CLI command we use:

```bash
vault kv patch secret/ourteam/config foo=bar
```

**Comment by mp911de** [comment]
Good proposal. Do you want to submit a pull request?

**Comment by yfaney** [comment]
Sure, I'll kick the work off and post its pr.
