### ISSUE TITLE
Extend LeaseEndpoints to allow path-based lease revocation

### ISSUE THREAD

**Issue by ThomasKasene** [spring-projects/spring-vault#588]
Hey, there!

I'm sorry for bringing this up again, but I feel like #480 was never fully explored or explained, and it's still an annoyance due to false positives in error logs as well as a slight security risk.

I don't believe most admins will grant all their applications access to `sys/leases/revoke`. Doing so would give those applications the ability to revoke any lease as long as they know the lease ID.

With that assumption in mind, I can only see two possible solutions:
- Disable revoking of leases when an application shuts down since it's likely to fail anyway. This only really removes the error messages from the log, but doesn't actually solve the main problem with dangling leases
- Allow applications to revoke a specific lease by their ID via the `sys/leases/revoke-prefix/` endpoint, which is documented [here ](https://www.vaultproject.io/api-docs/system/leases#revoke-prefix)

I know the `revoke-prefix` endpoint also has its caveats, most notably that it'll revoke anything that's "after" whatever prefix you define. I do believe it should be up to each project/organization to decide if they want to leverage it, however. It is possible to give an application access to a specific lease ID while rejecting all other revocation attempts, for example.

One relatively simple (and possibly naïve, I haven't looked through the whole `spring-vault` code base!) solution to the problem could perhaps be to add another constant to the `LeaseEndpoints` enum. That makes it easy for people to opt in by setting the `spring.cloud.vault.config.lifecycle.lease-endpoints` to `SysLeasesPrefix` (or whatever the name ends up being).
```java
// TODO: Come up with a better name, maybe
SysLeasesPrefix {

	@Override
	public void revoke(Lease lease, RestOperations operations) {

		// TODO: Consider if this is secure enough or if it needs to be sanitized
		String endpoint = "sys/leases/revoke-prefix/" + lease.getLeaseId();
		operations.put(endpoint, null);
	}

	@Override
	public Lease renew(Lease lease, RestOperations operations) {

		return SysLeases.renew(lease, operations);
	}
};
```

In any case, keep up the good work! 😃

**Comment by mp911de** [comment]
> I'm sorry for bringing this up again, but I feel like #480 was never fully explored or explained

No worries. The referenced ticket had a strong focus on request body parameters vs. request path parameters.

> I don't believe most admins will grant all their applications access to sys/leases/revoke.

That's a fair assumption and probably a good measure to disallow `/revoke/{leaseId}` as a sufficient number of attempts may yield a hit to revoke a lease that wasn't controlled by the application.

It makes a lot of sense to introduce a new enum constant that allows revocation through the prefix. Since we use the full lease Id, we don't accidentally revoke other leases.

While being on it, it probably makes also sense to revisit enum constant naming. Introducing an alias (well, delegate) `Leases` als alternative to `SysLeases` makes it easier to come up with a name. `Prefix` or `RevokeByPrefix` are names that could help to find a good constant name.

We also should switch the default in `SecretLeaseContainer` from `Legacy` to `SysLeases`.

In any case, feel free to submit a pull request.

**Comment by ThomasKasene** [comment]
Thanks for your thoughts and ideas, I'll give it a go!

Another question that came up is: should this be implemented only for the `/sys/leases` version of the API, or for the legacy version as well? I'm struggling to find the documentation for that API so I'm not even sure if such an endpoint exists, but I need to know if I'm to add a 4th enum constant.

> Introducing an alias (well, delegate) Leases als alternative to SysLeases makes it easier to come up with a name.

Do you mean I should add a new constant, `Leases`, which behaves exactly like `SysLeases`, or do you just mean to use the word `Leases` as a tool for coming up with a descriptive name for the new constant?

The most unambiguous constant name I can come up with is `SysLeasesUsingRevokePrefix`, which incorporates the `/sys/leases` version of the API and also which endpoint it uses to revoke leases. I honestly feel like these two operations should've been separated because that would've made it slightly easier to add permutations like this later on. But that's difficult to predict ahead of time.

Regarding changing the default implementation from `Legacy` to `SysLeases`, maybe that warrants its own PR? That way it won't interfere with this issue in case you want to add this to the 2.2.x train.

**Comment by mp911de** [comment]
> should this be implemented only for the /sys/leases

Yes, please. We don't want to evolve around the legacy endpoints as we're going to deprecate that constant anyways.

> Do you mean I should add a new constant, Leases, which behaves exactly like SysLeases

Exactly.

**Comment by ThomasKasene** [comment]
Should I deprecate `SysLeases` then, in favour of `Leases`, or will that happen at some later time?

Right now the enum contains the following constants:

- `Legacy`
- `SysLeases`
- `Leases`
- `LeasesRevokedByPrefix`

Do you think that's okay, or should I brainstorm the name even more?

**Comment by mp911de** [comment]
I think that's fine for now. Feel free to deprecate `SysLeases` in favour of `Leases`.

**Comment by ThomasKasene** [comment]
Alright, I created a PR and I believe it's ready for a review 😃
