### ISSUE TITLE
Change default SecretLeaseContainer.leaseEndpoints from Legacy to Leases

### ISSUE THREAD

**Issue by ThomasKasene** [spring-projects/spring-vault#589]
As suggested in #588, maybe the time is ripe for replacing the default selection of `SecretLeaseContainer.leaseEndpoints` from `LeaseEndpoints.Legacy` to `LeaseEndpoints.SysLeases`, or alternatively, the new option that's being added in #588?

**Comment by ThomasKasene** [comment]
Correction: #588 now deprecates `LeaseEndpoints.SysLeases`, so the new default should be one of these instead:

- `LeaseEndpoints.Leases`
- `LeaseEndpoints.LeasesRevokedByPrefix`

**Comment by mp911de** [comment]
That's in place now.
