### ISSUE TITLE
Support kv v2 through spring-data repositories

### ISSUE THREAD

**Issue by MarkRobbo** [spring-projects/spring-vault#593]
My previous implementation used kv v1 and something similar to the following standard repository setup:

```
@Secret(value = "example/location")
class Credentials {
    @Id String id;
    String data1;
    String data2;
}

interface CredentialsRepository extends CrudRepository<Credentials, String> {
}
```

It would be great if spring-vault also supported something similar to the following for kv v2 for upgrading (or some sort of different versioned repository interface)

```
@Secret(value = "example/location")
class Credentials {
    @Id String id;
    String data1;
    String data2;
}

interface CredentialsRepository extends CrudRepository<Versioned<Credentials>, String> {
}
```

This would prevent the need for manually implementing this sort of interface using `VaultVersionedKeyValueOperations`

**Comment by mp911de** [comment]
Do you want to give it a try by submitting a pull request? We also could make use of `@Version` to map the CAS parameter/secret version.

**Comment by MarkRobbo** [comment]
I've done some further investigation and there's probably two parts to this:

1. Allow spring-data repositories to work with un-versioned `@Secret` using the kv2 backend - the fix for this seems to be rather than using `KeyValueTemplate` use `VaultKeyValueTemplate1/VaultKeyValueTemplate2`. `VaultTemplate` appears to have some logic for this already but the repositories don't seem to use this
2. The above update to support versioned secrets when using the kv2 backend, which is more complex

I'm struggling to get to grips with the project more compared to other spring projects I'm familiar with due to different patterns in the use of autoconfiguration and beans.

**Comment by mp911de** [comment]
Repository support was added before we had `VaultKeyValueOperations` and therefore, we never adopted the code to `VaultKeyValueOperations`. Given that direct `VaultOperations` comes with its own advantages (e.g. full flexibility) I'm not sure whether we require migrating repository support (namely `VaultKeyValueAdapter`) to `VaultKeyValueOperations` at all.

The distinction, whether to use KV1 or KV2 should be derived from the keyspace that maps to the context path. We have already a `KeyValueDelegate` that distinguishes between both backend versions to retrieve a secret. It would make sense to reuse or extend that class as needed.

Happy to guide you through Spring Vault if you like.
