### ISSUE TITLE
Non-atomic updates to LeaseAwareVaultPropertySource cause leave property source empty until SecretLeaseCreatedEvent

### ISSUE THREAD

**Issue by domingogomez-asto** [spring-projects/spring-vault#594]
As discussed in https://github.com/spring-cloud/spring-cloud-vault/issues/446 there is a small gap of time between SecretLeaseExpiredEvent and SecretLeaseCreatedEvent that makes read of properties at that exact moment to throw IllegalArgumentException.

**Comment by mp911de** [comment]
That's fixed for version 2.3 RC1 now. We'd like to get feedback on this issue before backporting it to the 2.2.x line.
