### ISSUE TITLE
GcpCredentialSupplier uses deprecated GoogleCredential class

### ISSUE THREAD

**Issue by igouss** [spring-projects/spring-vault#600]
Project should use this dependency instead for GCP IAM authentication
https://github.com/googleapis/google-auth-library-java

**Comment by mp911de** [comment]
Feel free to submit a pull request adding another variant of `GcpIamAuthentication` using the mentioned library.

**Comment by igouss** [comment]
Can you take a look?
https://github.com/spring-projects/spring-vault/compare/master...igouss:UpdateGcpCredentialSupplier?expand=1

I have trouble running tests locally. But I did not really try.
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.springframework.vault:spring-vault-dependencies:pom:2.3.0-SNAPSHOT @ org.springframework.vault:spring-vault-parent:2.3.0-SNAPSHOT, /home/igoussev/spring-vault/pom.xml, line 108, column 16
```
One issue: see // TODO: Figure out how to set httpTransport on IamCredentialsClient

**Comment by igouss** [comment]
I found this warning while working on this. Sounds urgent.

https://cloud.google.com/iam/docs/migrating-to-credentials-api
> The IAM API also contains methods for signing JWTs and binary blobs. As of July 1, 2020, these methods are deprecated in the REST API and in all client libraries for the IAM API. You must migrate to the Service Account Credentials API before July 1, 2021.

**Comment by mp911de** [comment]
This issue went unnoticed. Starting with a pull request is a good idea. Instead of changing the existing `GcpIamAuthentication`, I'd suggest to introduce a new variant to not break existing code.

**Comment by andreasgebauer** [comment]
Would be nice to have the support for the IAM credentials API available in the next release. I created a PR yesterday. Let me know if this works for you

**Comment by mp911de** [comment]
Thanks a lot. Will have a look in the next few days.

**Comment by mp911de** [comment]
It makes sense to backport this change into the next service release given that the IAM API will stop working as of July this year.
