### ISSUE TITLE
Potentially unsafe usage of WebClient in ReactiveVaultTemplate

### ISSUE THREAD

**Issue by robotmrv** [spring-projects/spring-vault#612]
There are several unsafe places which could lead to resource (connections, byte buffers) leaks  
1. `mapOtherwise()`  could return `Mono.empty()` without `ClientResponse` consumption  
https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/core/ReactiveVaultTemplate.java#L338-L343
```java
	private static <T> Mono<? extends T> mapOtherwise(ClientResponse response, String path, HttpMethod method) {

		if (response.statusCode() == HttpStatus.NOT_FOUND && method == HttpMethod.GET) {
			return Mono.empty();//<-- 
		}

		return response.bodyToMono(String.class).flatMap(body -> {

			String error = VaultResponses.getError(body);

			return Mono.error(VaultResponses.buildException(response.statusCode(), path, error));
		});
	}
```

2. usage of unsafe deprecated `exchange()`. 
`WebClient.RequestHeadersSpec#exchangeToMono()` or `WebClient.ResponseSpec#toEntity()` could be used instead.

**Comment by mp911de** [comment]
Thanks a lot, we now moved off the deprecated API.
