### ISSUE TITLE
CertificateClientAuthentication does not work with PEM_KEYSTORE_TYPE (client certificate must be supplied)

### ISSUE THREAD

**Issue by RemiBou** [spring-projects/spring-vault#616]
I am trying to setup CertificateClientAuthentication from a PEM file (containing both cert and key) but I fail to make it work and always get an error "400 Bad Request: [{"errors":["client certificate must be supplied"]}".

I used these scripts (https://github.com/spring-projects/spring-vault/tree/master/src/test/bash) for generating my certificates. 
And for creating my pem file I added this :
```
cat  ${CA_DIR}/certs/client.cert.pem ${CA_DIR}/private/client.key.pem > ${CA_DIR}/private/client.key-cert.pem
```

And my java code for creating the CertificateClientAuthentication ("/work/ca/private/client.key-cert.pem" is a resource)

```java
VaultEndpoint vaultEndpointTLS = VaultEndpoint.from(new URIBuilder()
            .setHost("localhost")
            .setPort(8202)
            .setScheme("https")
            .build())
var  sslConfiguration = SslConfiguration
                .forTrustStore(new FileUrlResource(VaultClientTest.class.getResource("/work/keystore.jks")),
                        keystorePassword.toCharArray());
var sslConfigurationClient = new SslConfiguration(
                SslConfiguration.KeyStoreConfiguration
                        .of(new FileUrlResource(getClass().getResource("/work/ca/private/client.key-cert.pem")))
                        .withStoreType(SslConfiguration.PEM_KEYSTORE_TYPE),
                SslConfiguration.KeyConfiguration.unconfigured(),
                sslConfiguration.getTrustStoreConfiguration());
        ClientHttpRequestFactory clientHttpRequestFactory =
                ClientHttpRequestFactoryFactory.create(new ClientOptions(), sslConfigurationClient);
        ClientCertificateAuthentication clientCertificateAuthentication = new ClientCertificateAuthentication(
                RestTemplateBuilder.builder()
                        .requestFactory(clientHttpRequestFactory)
                        .endpointProvider(SimpleVaultEndpointProvider.of(vaultEndpointTLS))
                        .build()
        );
        clientCertificateAuthentication.login(); //fails here
```

The TLS connection is ok (from the logs). It works if I use the client-cert.jks instead of my PEM but I want my user to send a PEM file instead of a jks.

I followed the IntegrationTest for finding out how to use PEM_KEYSTORE_TYPE.
The [following test ](https://github.com/spring-projects/spring-vault/blob/25c3bf8fc0926d5c0914f6fa6a8cad724c819a4b/spring-vault-core/src/test/java/org/springframework/vault/client/ClientHttpRequestFactoryFactoryIntegrationTests.java#L66) does not check login but only sys/health which is opened by default. I guess it'll fail if we try to login because in this test we use only the ca certificate, client certificate are never setup.

**Comment by RemiBou** [comment]
I'm not a java/security expert but it seems like we don't use keys from the pem in org.springframework.vault.client.ClientHttpRequestFactoryFactory#loadFromPem : we keep only certificates.

**Comment by mp911de** [comment]
Care to submit a pull request?

**Comment by RemiBou** [comment]
Yes, sure !
