### ISSUE TITLE
Add ability to configure client TLS enabled protocol versions and cipher suites via Spring properties

### ISSUE THREAD

**Issue by mryangza** [spring-projects/spring-vault#635]
It would be useful if the enabled TLS protocol versions and cipher suites used by an HTTP client to Vault could be configurable via Spring properties (bound to the `org.springframework.vault.support.SslConfiguration` class). These could then be set on the SSL socket factory created by the underlying request factories created via the `org.springframework.vault.client.ClientHttpRequestFactoryFactory` class. It looks like Apache HTTP Components and Netty support setting this via their builders, I am unsure whether OkHttp does. It might require a custom SSL socket factory wrapper that decorates the sockets as they are created (before they are connected).

Thoughts? I am happy to attempt a PR.

**Comment by mp911de** [comment]
Sounds good. We have a config class for ssl that we use to configure the ssl context. Feel free to submit a pull request.

**Comment by mryangza** [comment]
Great, I've already spent some time implementing this, I'll try and finish it off in the next little while.
