### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/boot/Bootstrapper

### ISSUE THREAD

**Issue by igouss** [spring-projects/spring-vault#638]
I've got this error when I tried to use 3.0.1 version. It fails because I was using spring 
`spring-boot-gradle-plugin:2.3.7.RELEASE` had to change to `spring-boot-gradle-plugin:2.4.3` to fix it.

Should v3 branch declare min spring boot version dependency?

**Comment by mp911de** [comment]
Spring Vault doesn't depend on Spring Boot. Do you rather refer to Spring Cloud Vault?
