### ISSUE TITLE
Spring-vault transit api for hmac not working

### ISSUE THREAD

**Issue by amol-gaikwad** [spring-projects/spring-vault#658]
Spring vault version: 2.3.2
Vault version: 1.7.3
Authentication : Using appRole

I am facing one problem for hmac operation while using Spring-Vault.

Below hmac operation works.
 
**Working Request**
```
curl --location --request POST 'https://127.0.0.1:8200/v1/transit/hmac/default-mac/sha2-256' \
--header 'X-Vault-Token: s.NvdLGh4ohtgcXEShSCYfB73n' \
--header 'X-Vault-Request: true' \
--header 'Content-Type: application/json' \
--data-raw '{
    "input": "QW1vbCBHYWlrd2FkIHFhOCBDcnlwdG8tYXBpIDIuMTIgZGF0YWJhc2UgOQ=="
}'
```
 
 
But below API documentation says
https://www.vaultproject.io/api-docs/secret/transit#algorithm-1
 
```
POST /transit/hmac/:name(/:algorithm)
algorithm (string: "sha2-256") – Specifies the hash algorithm to use. This can also be specified as part of the URL.
 ```
Instead of passing algorithm as part of URL, Spring-vault is trying to pass it in body.
https://github.com/spring-projects/spring-vault/blob/main/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTransitTemplate.java#L361 

But then it returns 403.
 
**Non working Request:**
```
curl --location --request POST 'https://127.0.0.1:8200/v1/transit/hmac/default-mac' \
--header 'X-Vault-Token: s.NvdLGh4ohtgcXEShSCYfB73n' \
--header 'X-Vault-Request: true' \
--header 'Content-Type: application/json' \
--data-raw '{
    "input": "QW1vbCBHYWlrd2FkIHFhOCBDcnlwdG8tYXBpIDIuMTIgZGF0YWJhc2UgOQ==",
    "algorithm": "sha2-256",
    "key_version ": 1
}'
 
```
Respose:
 
```
{
    "errors": [
        "1 error occurred:\n\t* permission denied\n\n"
    ]
}
```
 
I will appreciate if you can explain how to get it working or whether it's a bug in spring-vault..

**Comment by amol-gaikwad** [comment]
Same is the case for hmac verify provided by https://github.com/spring-projects/spring-vault/blob/main/spring-vault-core/src/main/java/org/springframework/vault/core/VaultTransitTemplate.java#L430

**Comment by amol-gaikwad** [comment]
The workaround is to pass key = actual_key+algorithm to above VaultTransitTemplate methods.

**Comment by amol-gaikwad** [comment]
Is there a way to add salt to hmac ?

**Comment by mp911de** [comment]
I think this is a bug. I'm not sure why we try using the body for the algorithm. Would you be interested in submitting pull requests? One to fix the algorithm issue, and one to add support for salt?

**Comment by mp911de** [comment]
Actually, Vault supports both:

> This can also be specified as part of the URL

The algorithm can be part of the URL or part of the body.

>  "1 error occurred:\n\t* permission denied\n\n"

The 403 error happens because of your authentication configuration.
