### ISSUE TITLE
Add automatic rotation of secrets stored in generic backend

### ISSUE THREAD

**Issue by deichten** [spring-projects/spring-vault#68]
At the moment the renewal process is dependent on a lease_id and evaluating if a lease is renewable which is not the case for secrets stored in the generic backend which is by design not returning any leases. As indicated in the [documentation of Vault](https://www.vaultproject.io/docs/secrets/generic/index.html#quick-start) the client is supposed to check back the value after the `refresh_interval` expired. I was stumbling over this implementing some test code. I suggest to do a quick fix in the documentation as well as potentially add a new Renewal strategy, e.g. `REFRESH`, to have the `SecretLeaseContainer` schedule the refresh of the secrets retrieved.

**Comment by mp911de** [comment]
Added a note about the current behavior in the reference documentation for now. 

It makes sense to refresh generic secrets (if requested with `Renewal.ROTATE`) and update the `PropertySource` content. I'm not quite sure whether it makes sense to remove these secrets in an error case (token is no longer authorized to obtain the secrets (HTTP 403), secrets removed by an operator (HTTP 404)). Happy to receive feedback.

**Comment by crinacimpian** [comment]
When will there be a fix for "refresh generic secrets (if requested with Renewal.ROTATE) and update the PropertySource content"? And my feedback: remove secrets from PropertySource content on 403/ 404 error cases.

**Comment by mp911de** [comment]
This ticket is likely to be implemented for Spring Vault 1.1. Feel free to submit a PR.

**Comment by sworisbreathing** [comment]
Per https://www.vaultproject.io/api/secret/generic/index.html:

> it is possible to mount secret backends at any location

So to implement this we'll also need to expose some configuration properties to tell Spring Vault which paths map to generic secret backends. [Spring Cloud Vault supports this](https://github.com/spring-cloud/spring-cloud-vault/blob/v1.0.0.RELEASE/spring-cloud-vault-config/src/main/java/org/springframework/cloud/vault/config/VaultGenericBackendProperties.java#L47) but it appears to only support a single generic backend.

**Comment by sworisbreathing** [comment]
Also, we can't use the lease renewal api in vault for this, because it's not a renewable lease. So we'd need a separate mechanism to schedule reloading of generic secrets based on `lease_duration` (assuming it's > 0).

**Comment by mp911de** [comment]
I adjusted the title to secret rotation for the generic secret backend. The term `renewal` has in the Vault space a different meaning and since there's no lease associated with generic secrets lease renewal cannot be applied.

I think it's not necessary where the secret backend is mounted. `SecretLeaseContainer` recognizes renewal/rotation of secrets by the requested renewal mode and whether a `lease_id` is associated with the returned secret. 

Generic secret rotation can be identified with:
1. Secrets that requested rotation (`renewal` mode is `ROTATE`)
2. Secret has no `lease_id` attached
3. Secret has a `lease_duration` attached

Qualified secrets can be scheduled directly for renewal. Does this make sense?

**Comment by sworisbreathing** [comment]
> Generic secret rotation can be identified with:

>    Secrets that requested rotation (renewal mode is ROTATE)
>   Secret has no lease_id attached
>    Secret has a lease_duration attached

>Qualified secrets can be scheduled directly for renewal. Does this make sense?

Yeah, that makes sense. Is it something that could be added to `SecretLeaseContainer` or would it be better to create a new one for generic secrets?

**Comment by mp911de** [comment]
`SecretLeaseContainer` is the right place for generic secret rotation.

**Comment by sworisbreathing** [comment]
I've opened #95 to implement automatic rotation of generic secrets. I don't think it will work for secrets that are bound via `@Value` (at least in singleton-scoped beans). I've had a look through [the code in spring-beans](https://github.com/spring-projects/spring-framework/blob/v4.3.8.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.java) that handles binding `@Value` and it doesn't look like it updates field values once they've been set.

If you're expecting the values to change you probably want to query them from the `Environment` every time.

**Comment by mp911de** [comment]
@sworisbreathing Thanks, I'll take a look at your PR. `@Value` works as designed. Values are injected once and only once upon component initialization.
