### ISSUE TITLE
Add missing properties in `VaultCertificateRequest`

### ISSUE THREAD

**Issue by abremora** [spring-projects/spring-vault#682]
# Description

Several properties are missing in `VaultCertificateRequest`:
```
common_name
alt_names
ip_sans
uri_sans
other_sans           <-- missing
ttl
format               <-- missing
private_key_format   <-- missing
exclude_cn_from_sans
```
See: https://www.vaultproject.io/api-docs/secret/pki#generate-certificate

# Solution
Update `VaultCertificateRequest` and its implementation for `VaultPkiOperations.issueCertificate()` and `VaultPkiOperations.signCertificateRequest()`. Especially the mapping in `VaultPkiTemplate.createIssueRequest(VaultCertificateRequest certificateRequest)`.

Extracted issue from #477

**Comment by mp911de** [comment]
`private_key_format` added with #688
