### ISSUE TITLE
Vault seal operation fails

### ISSUE THREAD

**Issue by maniek45** [spring-projects/spring-vault#70]
When trying to seal vault v0.7.0 using VaultTemplate opsForSys().seal() I'm getting 500 error with message " missing client token".

**Comment by mp911de** [comment]
Seems Vault introduced the change silently. Flagging as enhancement because it's new to 0.7.0.

**Comment by maniek45** [comment]
I can see that in the spring-vault release M1 seal command was executed in SessionCallback but in release R1 without session?

**Comment by mp911de** [comment]
You're right, sorry, my bad.
