### ISSUE TITLE
Create keystore with password

### ISSUE THREAD

**Issue by abremora** [spring-projects/spring-vault#708]
No password will be set by `CertificateBundle.createKeyStore()`. There should be a new overload which provides a parameter to set the password. 

https://github.com/spring-projects/spring-vault/blob/dd9c3cfab8aca6ee4572f9c81b9a02000b2db480/spring-vault-core/src/main/java/org/springframework/vault/support/KeystoreUtil.java#L94

**Comment by mp911de** [comment]
Good suggestion. Feel free to submit a pull request.

**Comment by sodrac** [comment]
Hi @mp911de, if this issue is still available I'll like to work on it.

**Comment by mp911de** [comment]
Sure, feel free to submit a pull request.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.
