### ISSUE TITLE
disable SSL verification in Spring Vault

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-vault#709]
It will help in quick unit testing

**Comment by Nidhi-Tanwar14** [comment]
As of now, getting following exception:-
Cannot login using org.springframework.web.client.ResourceAccessException: I/O error on POST request for : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.springframework.vault.authentication.VaultLoginException: Cannot login using org.springframework.web.client.ResourceAccessException: I/O error on POST request for : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Nidhi-Tanwar14** [comment]
RestTemplate can give any of the below error if SSL certificate of the target host is not valid:

- PKIX path building failed: sun.security.provider.certpath
- PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
- javax.net.ssl.SSLHandshakeException: PKIX path building failed

**Comment by mp911de** [comment]
Please use plaintext. We do not plan to disable SSL verification.
