### ISSUE TITLE
Add support for /sys/generate-root endpoint

### ISSUE THREAD

**Issue by maniek45** [spring-projects/spring-vault#71]
It would be nice to have support for /sys/generate-root endpoint operations.

**Comment by mp911de** [comment]
Thanks for the feature proposal. It makes sense to revisit our Vault initialization arrangement to improve the operational experience. Right now, we support basic operations that are tied to authentication and secret backend interaction. 

Right now, `VaultOperations` allows you to interact with arbitrary Vault paths using `read(…)` and `write(…)` methods.

I'm setting this ticket to later. It requires further design and we want to learn from the upcoming release how Spring Vault is actually used.

**Comment by mp911de** [comment]
We decided to drop the edge-case. Use either `write` methods or `RestTemplate` within a callback.
