### ISSUE TITLE
Integration of Spring Vault with azure key vault

### ISSUE THREAD

**Issue by Nidhi-Tanwar14** [spring-projects/spring-vault#710]
This can be a good new feature

**Comment by Nidhi-Tanwar14** [comment]
From the Spring Vault offical site](https://spring.io/projects/spring-vault#overview), it supports HashiCorp’s Vault, and there are some examples with HashiCorp’s Vault. Does it support Azure key vault natively please?

From the azure documentation - (https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault), springboot starter is

<groupId>com.azure.spring</groupId>
  <artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
</dependency>

So, can there be provision for the spring vault integration with the azure key vault? 

Thanks a lot.

**Comment by Nidhi-Tanwar14** [comment]
According to the Spring Vault project's documentation,  it can only be used with Hashicorp Vault. Any possibility of using it with any other Vault service providers

**Comment by mp911de** [comment]
Azure Key Value is something different than HashiCorp Vault. Azure KeyValut can be used through [Spring Cloud Azure](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/spring-cloud-azure-starter-keyvault).
