### ISSUE TITLE
VaultException thrown without "cause" hides important information

### ISSUE THREAD

**Issue by CharlieReitzel** [spring-projects/spring-vault#713]
In general, exception handlers should preserve the original exception so eventually, a full stack trace to the original offending code can be logged.  This gives developer the ability to quickly zero in on the precise issue and time to resolve problems is dramatically reduced.

This principle is described by a SonarQube issue [RSPEC-1166](https://rules.sonarsource.com/java/RSPEC-1166).

I am finding that, in a number of places, the `spring-vault` project is suppressing the original exception.   The original message is usually logged, but the exact location where the exception was thrown is lost.

The fix is to simply include the original exception with `VaultException` - or derived type - as the "cause".

**Comment by mp911de** [comment]
How about submitting a pull request so we can continue the discussion over actual code changes?

**Comment by CharlieReitzel** [comment]
Looks I am just lucky.  I found only 3 cases.  But I'm encountering 1 of them.  Such is life.

Here are links to the lines of code.  Does that work?

1. [VaultTokenAdapter](https://github.com/spring-projects/spring-vault/blob/cd57bfb1602cc27295373d964daccd52bc2c9db3/spring-vault-core/src/main/java/org/springframework/vault/authentication/LoginTokenAdapter.java#L102)
2. [VaultLoginException](https://github.com/spring-projects/spring-vault/blob/cd57bfb1602cc27295373d964daccd52bc2c9db3/spring-vault-core/src/main/java/org/springframework/vault/authentication/VaultLoginException.java#L64)
3. [AbstractResult](https://github.com/spring-projects/spring-vault/blob/cd57bfb1602cc27295373d964daccd52bc2c9db3/spring-vault-core/src/main/java/org/springframework/vault/support/AbstractResult.java#L85)

**Comment by mp911de** [comment]
How exactly do you intend to extract a cause from a HTTP status code that isn't communicated as exception?
