### ISSUE TITLE
Injecting a list of values into a @VaultPropertySource is not working

### ISSUE THREAD

**Issue by oritaddar** [spring-projects/spring-vault#723]
I am using spring-vault-core. I have create some list type properties in my appilication.propertis and I am trying to inject it into a member type @VaultPropertySource in one of my classes with no success , I tried different ways and none of them have worked.

appilication.properties: vault.kv.paths=kv/cti-server,kv/server/prod/Sybase

Class:
@VaultPropertySource("#{${vault.kv.path}.split(',')}")
Or
@VaultPropertySource(
      value = {
            "#{'${vault.kv.paths}'.split(',')}"
      })

**Comment by mp911de** [comment]
`@VaultPropertySource` doesn't support SpEL expressions, only references to properties that can be resolved through `Environment.resolveRequiredPlaceholders(…)`. Additionally, the expression you're trying to use resolves to an array, and that doesn't work here either as we require a single string.
