### ISSUE TITLE
Disable vault spring boot

### ISSUE THREAD

**Issue by piyush-narvar** [spring-projects/spring-vault#724]
I have a spring boot project where I wanted to disable the vault conditionally. 
`      <dependency>
            <groupId>org.springframework.vault</groupId>
            <artifactId>spring-vault-core</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>`
The version I am using. How can I do that?

I have spring profile-based configurations in the code.

**Comment by mp911de** [comment]
Spring Vault isn't controlling Spring Boot or the like. You can either disable the auto configuration, bootstrap context, or remove Vault from `spring.config.import` but all these are Spring Boot topics.
