### ISSUE TITLE
VaultTransitOperations with versioned keys

### ISSUE THREAD

**Issue by dermotmburke** [spring-projects/spring-vault#726]
The Transit Engine API (https://www.vaultproject.io/api-docs/secret/transit#encrypt-data) allows the inclusion of a "key_version" attribute when calling encrypt endpoint. There does not seem to be any way to include this attribute when calling VaultTransitOperations.encrypt(). Is there something I am missing or is this functionality not currently available?

**Comment by mp911de** [comment]
We don't support versioned keys yet. It would make sense to have methods accepting a `TransitKey` object that specifies the key name and, optionally the version. Feel free to come up with a pull request if you like so we can move forward on this topic.

**Comment by dermotmburke** [comment]
Thanks for confirming @mp911de
