### ISSUE TITLE
3.X : AWS IAM Authentication forced to send a region

### ISSUE THREAD

**Issue by vmeunier** [spring-projects/spring-vault#736]
Hello,

Starting from 3.0.0.X the region used during AwsIamAuthentification is the one defined in the metadata of the EC2 instance.

We can override the region via a property in spring cloud : 

```text
cloud.aws.region.auto 
cloud.aws.region.static
```

But, if we do so, any AWS request we do from our code will use that region.

Our Vault only has 1 STS Endpoint configured : us-east-1 (which is the default one), but we do deploy services in eu-west-1 and eu-west-3.

I would like to be able to still "not send" the region, just like the Vault CLI does in command line. Is it possible to add a property to disable that feature ? Just like it was in previous version 2.4.x ?

Sample of the error (via vault cli) :

```shell
vault login -address=<our_vault_url> -method=aws role=<the_role>
Key                      Value
---                      -----
token                    hvs.CAESIMhoBAdkYlpO...
```

```shell
vault login -address=<our_vault_url> -method=aws region=auto role=<the_role>

Error authenticating: Error making API request.

URL: PUT https://vault/v1/auth/aws/login
Code: 400. Errors:

* error making upstream request: received error code 403 from STS: <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>Credential should be scoped to a valid region. </Message>
  </Error>
  <RequestId>rid</RequestId>
</ErrorResponse>
```
`region=auto` is the way Spring-Vault works right now if i'm not mistaken.

I have the stacktrace in Java if you want.

Regards,
Vincent;

**Comment by mp911de** [comment]
We're using `Aws4Signer` and `Aws4SignerParams` to compute the signature. The region must be non-null and is provided through `AwsRegionProvider`. How would that work with `auto`?

**Comment by vmeunier** [comment]
for example with the cli : 

```text
vault login  -address="https://vault" -method=aws region=us-east-1 role=<role>

Authentication was successful, but the token was not persisted. The resulting
token is shown below for your records.

Key                      Value
---                      -----
token                    hvs.CAESIO_if...
...
```

Which can be done using 

```properties
cloud.aws.region.auto=false
cloud.aws.region.static=us-east-1
```

But this is a global configuration, it is used everywhere, not just for interacting with Vault.

**Comment by mp911de** [comment]
You can generally implement your own authentication mechanism with an older signer version if you wish by implementing `ClientAuthentication`.
