### ISSUE TITLE
Add ca_chain property to Certificate

### ISSUE THREAD

**Issue by bshelton** [spring-projects/spring-vault#746]
As of Vault 1.11, the generate cert and key pki endpoint now returns the ca_chain. Is this something that we can add? If so, I will submit a PR for this. 

Reference: https://developer.hashicorp.com/vault/api-docs/secret/pki#generate-certificate-and-key

Solution: 
Update spring-vault/blob/main/spring-vault-core/src/main/java/org/springframework/vault/support/Certificate.java CertificateBundle.java

**Comment by mp911de** [comment]
This looks like a duplicate of #648. Can you confirm whether this works for you?
