### ISSUE TITLE
Lacking Documentation

### ISSUE THREAD

**Issue by aizotov-aspiration** [spring-projects/spring-vault#76]
Does this setup look right to you?

```
VaultEndpoint vaultEndpoint = VaultEndpoint.create("my-vault.my-domain.com", 8200);

RestTemplate restTemplate = VaultClients.createRestTemplate(vaultEndpoint, new SimpleClientHttpRequestFactory());
ClientAuthentication clientAuthentication = new AwsEc2Authentication(restTemplate);

VaultTemplate vaultTemplate = new VaultTemplate(vaultEndpoint, clientAuthentication);

VaultResponse writeResponse = vaultTemplate.write("secret/foo/bar", ImmutableMap.of("foo-secret-key", "bar-secret"));

VaultResponseSupport<Map> readResponse = vaultTemplate.read("secret/foo/bar", Map.class);
```

**Comment by mp911de** [comment]
This kind of questions rather belongs to [StackOverflow](https://stackoverflow.com/questions/tagged/spring-vault). Your setup looks correct. In doubt check out [`AbstractVaultConfiguration`](https://github.com/mp911de/spring-vault/blob/6875da1a75accdf4233d28639fb2ad47f3a9c69d/spring-vault-core/src/main/java/org/springframework/vault/config/AbstractVaultConfiguration.java#L153-L153).

**Comment by aizotov-aspiration** [comment]
Thank you 👍
