### ISSUE TITLE
Extra forward slash in authentication path

### ISSUE THREAD

**Issue by aizotov-aspiration** [spring-projects/spring-vault#77]
This is the URL that is generated when attempting to do AwsEc2Authentication#login

`https://my-vault.my-domain.com:8200/v1//auth/aws-ec2/login`

Maybe this happens because the base url ends with a forward slash and the login request begins with a forward slash? Seems like it is just concatenating the two strings.

https://github.com/spring-projects/spring-vault/blob/d3491dd7121b017e3234f7ba26c63ca46f8de23a/spring-vault-core/src/main/java/org/springframework/vault/client/VaultClients.java#L114

https://github.com/spring-projects/spring-vault/blob/d8d85e1a67405c41a4ffa35aca2de74ed5d62527/spring-vault-core/src/main/java/org/springframework/vault/authentication/AwsEc2Authentication.java#L106

Perhaps I am missing some piece of configuration?

This is my setup. Call to login is triggered by the write
```
VaultEndpoint vaultEndpoint = VaultEndpoint.create("my-vault.my-domain.com", 8200);

RestTemplate restTemplate = VaultClients.createRestTemplate(vaultEndpoint, new SimpleClientHttpRequestFactory());
ClientAuthentication clientAuthentication = new AwsEc2Authentication(restTemplate);

VaultTemplate vaultTemplate = new VaultTemplate(vaultEndpoint, clientAuthentication);

VaultResponse writeResponse = vaultTemplate.write("secret/foo/bar", ImmutableMap.of("foo-secret-key", "bar-secret"));
```

**Comment by mp911de** [comment]
[`PrefixAwareUriTemplateHandler`](https://github.com/mp911de/spring-vault/blob/d3491dd7121b017e3234f7ba26c63ca46f8de23a/spring-vault-core/src/main/java/org/springframework/vault/client/VaultClients.java#L122-L122) is stripping the URL during expansion. Which Spring Framework Version are you using?

**Comment by aizotov-aspiration** [comment]
I'm using Spring Boot 1.2.6.RELEASE

**Comment by mp911de** [comment]
Please upgrade to at least Spring Framework 4.3.0. Spring Boot 1.2.6 comes with Spring Framework 4.1.7 (that's not supported).
