### ISSUE TITLE
Spring Vault documentation broken link

### ISSUE THREAD

**Issue by rawfg** [spring-projects/spring-vault#788]
The [Token Lifecycle](https://docs.spring.io/spring-vault/docs/current/reference/html/#vault.authentication.session) chapter has a bullet list with tokens:

![image](https://user-images.githubusercontent.com/910461/235584330-8c51e77e-4d0d-4e74-afa6-595b474a3a8c.png)

The second list item `LoginToken` is broken and points to [non-existing JavaDoc page](https://docs.spring.io/spring-vault/docs/2.2.3.RELEASE/api/org/springframework/vault/support/LoginToken.html)

**Comment by mp911de** [comment]
That's fixed now and will become visible after releasing our documentation.
