### ISSUE TITLE
Need address without port

### ISSUE THREAD

**Issue by aizotov-aspiration** [spring-projects/spring-vault#79]
How can I talk to vault without specifying a port? I have vault running in HA mode behind a load balancer than handles port routing. I need the address to look like
`https://my-vault.my-domain.com/v1/secret/foo`

**Comment by spencergibb** [comment]
Isn't that the same as `https://my-vault.my-domain.com:443/v1/secret/foo`?

**Comment by aizotov-aspiration** [comment]
Wow yes it is... thank you!!!!!
