### ISSUE TITLE
Support for deleting metadata and secrets

### ISSUE THREAD

**Issue by aawwsed10** [spring-projects/spring-vault#801]
is [VaultKeyValueMetadataOperations](https://docs.spring.io/spring-vault/docs/2.3.1/api/org/springframework/vault/core/VaultKeyValueMetadataOperations.html) removed in current version 3.0.2? I am trying to permanently destroy all versions and metadata under a path, is there an equivalent call that can destroy everything under a path?

              Support for deleting Key-Value metadata was introduced with #432.

_Originally posted by @mp911de in https://github.com/spring-projects/spring-vault/issues/568#issuecomment-659925339_

**Comment by mp911de** [comment]
No, why should it be removed? You can access metadata operations via `VaultOperations.opsForVersionedKeyValue(…).opsForKeyValueMetadata()`.

The operations map to what is possible with the CLI.
