### ISSUE TITLE
SPRING_CLOUD_VAULT_CONFIG_LIFECYCLE_ENABLED disabling not working

### ISSUE THREAD

**Issue by nemadev888** [spring-projects/spring-vault#814]
When We set the false value for SPRING_CLOUD_VAULT_CONFIG_LIFECYCLE_ENABLED, its not working properly. its still initiating the call for /v1/auth/token/renew-self. 
Using spring boot version: 2.5.0
Spring cloud vault version: 3.0.2

**Comment by mp911de** [comment]
The config property you're looking for is `spring.cloud.vault.session.lifecycle.enabled`.
