### ISSUE TITLE
EnvironmentVaultConfiguration does not check for spring.cloud prefix by default. 

### ISSUE THREAD

**Issue by alvonellos** [spring-projects/spring-vault#842]
I was using this in my project, and following this guide:[Getting Started]( https://spring.io/guides/gs/vault-config/) , I specified my configs as follows: 

```
spring.cloud.vault.uri=${URI}
spring.cloud.vault.token=${TOKEN:}
spring.cloud.vault.scheme=https
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=kv
spring.cloud.vault.kv.version=v1
spring.cloud.vault.kv.profile-separator='/'
spring.cloud.vault.kv.default-context=application
spring.cloud.vault.kv.application-name=${HOSTNAME}
spring.config.import=vault://
```

And noticed that there was an issue with my configs because vaultEndpoint() inside: org/springframework/vault/config/EnvironmentVaultConfiguration.java, does not check for location spring.cloud.vault.uri, as well as vault.uri. I could set a prefix using: [Prefix ](https://www.baeldung.com/spring-boot-env-variable-prefixes), but I think it should check this by default. 

I'll submit a pull request making the change, if that's ok?

**Comment by alvonellos** [comment]
Inside 	

```
@Override
	public VaultEndpoint vaultEndpoint() {

		String uri = getProperty("vault.uri");
		if (uri != null) {
			return VaultEndpoint.from(URI.create(uri));
		}

		throw new IllegalStateException("Vault URI (vault.uri) is null");
	}
```

getProperty does not check for common locations, such as spring.cloud, which is used commonly in instructions.

**Comment by alvonellos** [comment]
I made the code changes, and then tested manually and then made sure that all the unit tests pass.

**Comment by mp911de** [comment]
This is by design as Spring Vault is not Spring Cloud Vault and `EnvironmentVaultConfiguration` is part of Spring Vault and not the Boot-based variant.
