### ISSUE TITLE
Leases no longer revoked after stopping SecretLeaseContainer

### ISSUE THREAD

**Issue by NoureddineDahmen** [spring-projects/spring-vault#855]
I reopen this issue related to https://github.com/spring-projects/spring-vault/issues/844
We tested the version 3.1.1 and and unfortunately we still have the issue.

Best regards,

**Comment by mp911de** [comment]
Can you check your shutdown debug logs regarding Vault communication and debug what happens for you in `SecretLeaseContainer.destroy()` as there is the code path to revoke secrets?

**Comment by NoureddineDahmen** [comment]
Hello @mp911de , I'm sorry for the delay to give feedback .
In Debug , the method SecretLeaseContainer.destroy() is not called when we use ConfigData and it well called when we use Boostrap Config.
 
Best Regards,
