### ISSUE TITLE
Page not found for 2.3.3 reference doc

### ISSUE THREAD

**Issue by scordio** [spring-projects/spring-vault#858]
From https://spring.io/projects/spring-vault#learn, clicking on the Reference Doc link for version 2.3.3 leads to a page not found error: https://docs.spring.io/spring-vault/docs/2.3.3/reference/html/

**Comment by mp911de** [comment]
Thanks for letting us know, that's fixed now. Might require a refresh to reset your cache.

**Comment by scordio** [comment]
Thanks a lot!
