### ISSUE TITLE
DefaultUriTemplateHandler.insertBaseUrl adds extra / to URL

### ISSUE THREAD

**Issue by xiab71** [spring-projects/spring-vault#86]
I have built a SDK using Spring-Vault 1.0.0.M2. It works fine until I switched to 1.0.0.RELEASE. Stepping into the code, I have found the URL sent to Vault has extra `/` -- http://127.0.0.1:8200/v1//sys/auth/cert. Further looking into the code, there is a line (#121) in
DefaultUrlTemplateHandler.insertBaseUrl(UriComponents uriComponents) 

`String url = getBaseUrl() + uriComponents.toUriString();`

I think to be defensive, the code should first check if there is any leading/trailing / before concatenates the string to avoid the extra / in the URL. Currently, the issue basically blocks me from using GA version in the SDK.

**Comment by mp911de** [comment]
Which Spring Framework version are you using? Spring Vault requires at least Spring Framework 4.3.0.

**Comment by xiab71** [comment]
Here is a snippet from my SDK pom.xml. Spring Framework version should be fine.

`            <dependency>
                <groupId>org.springframework.vault</groupId>
                <artifactId>spring-vault-core</artifactId>
                <version>1.0.0.RELEASE</version>
            </dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-context</artifactId>
				<version>4.3.4.RELEASE</version>
			</dependency>            
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-expression</artifactId>
				<version>4.3.4.RELEASE</version>
			</dependency>            			
			<dependency>
			    <groupId>org.springframework</groupId>
			    <artifactId>spring-core</artifactId>
			    <version>4.3.4.RELEASE</version>
			</dependency>            
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-beans</artifactId>
                <version>4.3.4.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-aop</artifactId>
                <version>4.3.4.RELEASE</version>
            </dependency>
			<dependency>
			   	<groupId>org.springframework</groupId>
    			<artifactId>spring-test</artifactId>
    			<version>4.3.4.RELEASE</version>
			</dependency>                                   `

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by mp911de** [comment]
We're using a custom `DefaultUriTemplateHandler`([`PrefixAwareUriTemplateHandler`](https://github.com/spring-projects/spring-vault/blob/86bc5721f06c7b4b1bb6d7a365f59909b2c17969/spring-vault-core/src/main/java/org/springframework/vault/client/VaultClients.java#L143-L159)) to build the appropriate URL and strip/add slashes as needed.

In particular, it's the `spring-web` dependency that is required to be 4.3. Earlier versions will skip prefix/slash sanitization. I wasn't able to reproduce the issue using Spring Framework 4.3.4.RELEASE.

Can you provide us a minimal reproducible test case? A Github repo or Gist containing the code should be sufficient.

**Comment by xiab71** [comment]
Thanks for the reply. I will try to provide a reproducible test case.
