### ISSUE TITLE
Leases no longer revoked after stopping SecretLeaseContainer #855

### ISSUE THREAD

**Issue by NoureddineDahmen** [spring-projects/spring-vault#862]
Hello @mp911de  i just create the issue from another  Leases no longer revoked after stopping SecretLeaseContainer #855

Hello @mp911de , I'm sorry for the delay to give feedback .
In Debug , the method SecretLeaseContainer.destroy() is not called when we use ConfigData and it well called when we use Boostrap Config.

Best Regards,

**Comment by mp911de** [comment]
Thanks a lot for the detail. That helps to isolate the problem.

**Comment by mp911de** [comment]
Duplicate of #855
