### ISSUE TITLE
What is the property value to set for certificate authentication name?

### ISSUE THREAD

**Issue by aram535** [spring-projects/spring-vault#864]
I'm setting up an cert authentication but can't seem to find the option value to set for the cert auth name.   

https://docs.spring.io/spring-cloud-vault/docs/current/reference/html/#common-application-properties doesn't seem to contain any entries for the cert auth other than the mount name. 

```
curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" https://127.0.0.1:8200/v1/auth/cert/certs?list=true
```
Reference: https://github.com/spring-projects/spring-vault/pull/780

**Comment by mp911de** [comment]
The certificate role name isn't mapped as property. Can you file a ticket in https://github.com/spring-cloud/spring-cloud-vault/?
