### ISSUE TITLE
Incorrect documentation links

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-vault#869]
On https://spring.io/projects/spring-vault#learn there are two broken links:

* 3.2.0-SNAPSHOT links to https://docs.spring.io/spring-vault/reference, which shows the documentation for version 3.1.1.
* 2.3.4-SNAPSHOT doesn't have any links.

For 3.1.x and later, it looks like https://docs.spring.io/spring-vault/reference/{$version} is the correct URL format:

* 3.2.0-SNAPSHOT: https://docs.spring.io/spring-vault/reference/3.2.0-SNAPSHOT
* 3.1.1: https://docs.spring.io/spring-vault/reference/3.1.1

**Comment by mp911de** [comment]
That's fixed now. Thanks for letting us know.
