### ISSUE TITLE
LifecycleAwareSessionManager renewal starts eventually

### ISSUE THREAD

**Issue by TimShi** [spring-projects/spring-vault#87]
In LifecycleAwareSessionManager, the static variable REFRESH_PERIOD_BEFORE_EXPIRY is used to calculate when a token will be renewed. This value is set to 5 seconds, meaning token renewal will happen at (loginToken.getLeaseDuration() - REFRESH_PERIOD_BEFORE_EXPIRY) seconds from the time the token is obtained.

This is an issue because loginToken.getLeaseDuration() is the duration of the lease, not time to live.

What this means is in the following case, the token would have already expired when the renewal triggers:

1. Create token with lease duration set to 1 min.
2. Wait for 10 seconds
3. Start the spring application using this token. At this time, the token's lease duration is 60 seconds, but its TTL is 50 seconds (since we waited for 10 seconds before using this token).

LifecycleAwareSessionManager will schedule renew at 60 - 5 = 55 seconds from the current time. But since the token's TTL is 50 seconds, it will have already expired.

Even if the token is used right away after creation, this case can still happens if the spring application takes more than 5 seconds to start.

Proposed solution: make REFRESH_PERIOD_BEFORE_EXPIRY configurable through Vault properties.

**Comment by TimShi** [comment]
Is there any work around at the mean time? I tried to provide my own SessionManager (i.e. a tweaked version of LifecycleAwareSessionManager), but the issue I run into is LoginToken is not visible outside of its package. So in my custom LifecycleAwareSessionManager I can't check if the token is instance of LoginToken and get its lease duration.

**Comment by mp911de** [comment]
There's currently no workaround.  We will fix the delayed trigger calculation. Token renewal is scheduled immediately after obtaining the token with a `TaskScheduler` but the scheduler asks the trigger to provide a next execution date. This could be at any time. We will determine the next renewal time upfront so any delays in the `TaskScheduler` should not affect expiry. 

I initially assumed that's an enhancement but after realizing the possibility of delays, I labeled this issue as a bug.

Additionally, we will allow customization. `LifecycleAwareSessionManager` is immutable (from an external perspective) and I'd like to keep it that way. We can make `LoginToken` public and provide a `RefreshTrigger` interface that allows you to compute the refresh time.

Does this make sense?

**Comment by TimShi** [comment]
Also I think the refresh time probably should be calculated based on TTL instead of lease duration (or creation_ttl).

For example, if you create a token using:

```vault token-create --ttl=10m -wrap-ttl="24h"```

And then look up the token property using the wrapped_accessor, 

```vault token-lookup -accessor $wrapped_accessor```

you will see the following

```
Key             	Value
---             	-----
creation_time   	1493666164
creation_ttl    	600
display_name    	token
explicit_max_ttl	0
id              	
meta            	<nil>
num_uses        	0
orphan          	false
path            	auth/token/create
policies        	[root]
renewable       	true
ttl             	491
```

The ttl value is always decreasing, it shows the current ttl remaining, whereas creation_ttl (also called lease_duration in the unwrap response) is always the same.

Refresh time calculated based on lease_duration can be off by a lot of the token was not used immediately after it was created.

**Comment by mp911de** [comment]
I think that are two different issues

1. The first issue is related to delayed renewal/configuration of the period before token renewal. 
2. The second issue is related to cubbyhole authentication. Configuration of the renewal period does not really help here as the renewal period is static. It's not intended to consider delays between the token TTL start and application start. I created a second issue to perform a self-lookup after unwrapping the token and use the remaining TTL for the initial renewal.

**Comment by TimShi** [comment]
Agreed.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by TimShi** [comment]
If I want to provide my own implementation of RefreshTrigger, how would I hook it into LifecycleAwareSessionManager? Or should I provide my own LifecycleAwareSessionManager bean?

**Comment by mp911de** [comment]
You're talking right now about Spring **Cloud** Vault: 

Provide your own bootstrap configuration (add it to your project-specific [`META-INF/spring.factories`](https://github.com/spring-cloud/spring-cloud-vault/blob/7a09c9875f3ed22383d988c1a78bb6fdc79c71d8/spring-cloud-vault-config/src/main/resources/META-INF/spring.factories)) that configures a `LifecycleAwareSessionManager`. You can create `RestOperations` and `VaultEndpoint` the same way as `VaultBootstrapConfiguration` does. 

If you have further questions to Spring Cloud Vault, please post a question on StackOverflow or create a ticket in https://github.com/spring-cloud/spring-cloud-vault if there's something to fix.
