### ISSUE TITLE
Revoke lease error

### ISSUE THREAD

**Issue by eugene7772** [spring-projects/spring-vault#883]
Hi, i need help with deleting leases. If this problem has already been solved somewhere, please provide a link.
Details of the problem:
1. In Vault i am create database engine and dynamic role for this.
2. I have kuber role for auth with max ttl.
If i set max ttl for kuber token = 5 min and for database dynamic role max ttl = 6 min, then after expire token - database lease will delete. But on server after 1 min (6 - 5 min) in Map renewals (SecretLeaseContainer) this lease will try to renew. In vault on this moment lease deleted. And this provokes an error - Status 400 Bad Request lease not found. What can I do other than set same max ttl?
If you need logs or something else let me know.

**Comment by mp911de** [comment]
This has been fixed with #815 in version [3.1.2](https://github.com/spring-projects/spring-vault/releases/tag/3.1.2).
