### ISSUE TITLE
Allow AWS-EC2 nonce configuration

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#89]
AWS EC2 authentication currently calculates a nonce on first use. It's not possible to obtain the nonce from Vault or supply the nonce externally.

**Comment by meatlewis** [comment]
I'd really love to have this, not being able to supply the nonce is none optimal.

**Comment by mp911de** [comment]
Right now, you can override `AwsEc2Authentication.createNonce` and provide your own nonce. I started right now introducing a `Nonce` value object to be able to configure the nonce to a provided value in future versions.
