### ISSUE TITLE
Add PropertySource support

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#9]
Add support to retrieve data from Vault paths and use it as `PropertySource` inside a Spring `Environment`.

**Comment by spencergibb** [comment]
Huh. How would you see this as different from spring cloud vault config? I guess the autowiring?

**Comment by mp911de** [comment]
VaultPropertySource here is intended for Spring use without Boot. Similar
to '@PropertySource' in Spring Framework.
Spencer Gibb <notifications@github.com> schrieb am Sa. 24. Sep. 2016 um
22:17:

**Comment by spencergibb** [comment]
OK, can probably reuse `VaultPropertySource`.
