### ISSUE TITLE
Login Token Duration is assumed milliseconds instead of seconds

### ISSUE THREAD

**Issue by sworisbreathing** [spring-projects/spring-vault#96]
Per https://www.vaultproject.io/docs/concepts/lease.html#lease-durations-and-renewal:

>The lease duration is a Time To Live value: the time in seconds for which the lease is valid. A consumer of this secret must renew the lease within that time.

However it looks like LifecycleAwareSessionManager [assumes lease durations are in milliseconds](https://github.com/spring-projects/spring-vault/blob/e428cbf846e7e91b8ae30fc7575c306ae2e1848d/spring-vault-core/src/main/java/org/springframework/vault/authentication/LifecycleAwareSessionManager.java#L324)

To verify, run a simple client app with `-Dorg.apache.http.wire=debug` and watch your login token get renewed every second.

**Comment by zonybob** [comment]
Any ETA for 1.0.2 release? Thanks!

**Comment by mp911de** [comment]
I updated the schedule for [1.0.2](https://github.com/spring-projects/spring-vault/milestone/11) to June 16th.
