### ISSUE TITLE
Explore Vault cluster-awareness

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-vault#98]
Vault clustering since Vault 0.6.2 is nearly transparent from a client perspective if the client follows HTTP redirects. There are two scenarios that would benefit from a dedicated cluster-awareness:

1. Update the `VaultEndpoint` to send requests directly to the leader node
2. Send health checks to the leader/all nodes to gather a broader view over the cluster health state

**Comment by sworisbreathing** [comment]
Redirects were the default behavior prior to 0.6.2. After 0.6.2, the default behavior is for standby nodes to forward requests to the leader. As long as the HTTP client follows redirects, then the Vault version or the standby behavior shouldn't matter to the app.

**Comment by Athas1980** [comment]
Thats not entirely true @sworisbreathing the problem is if the master goes down. Say for a server restart then the cluster can't redirect to alternative.

**Comment by mp911de** [comment]
Right now, nothing to do here hence closing the ticket.

**Comment by VladRassokhin** [comment]
There's a problem when POST operation receives redirect response, since none of `ClientHttpRequestFactory`-ies configured to follow redirect for POST request API operation fails.

**Comment by mp911de** [comment]
Care to file a new ticket to support redirections?

**Comment by VladRassokhin** [comment]
@mp911de Created #184 feel free to rephrase, correct. Attached testing project there.
